### ISSUE TITLE
Allow a phase banner to appear above Masthead nav items

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#1039]
### Description
The Masthead component supports a nav property to specify Masthead nav items and this displays the nav items below the main heading section.

Unfortunately if a site includes a PhaseBanner this can only be displayed either below the nav section or above the main masthead. The Phasebanner should appear above the nav items.

As there is no other component to provide route based navigation styled like tabs this means I cannot recreate this design.

**Comment by ghost** [comment]
We're following the GDS model here in our Exemplar projects where the phase banner sits below the header but before the main page navigation / content:
https://design-system.service.gov.uk/components/phase-banner/

**Comment by hxltrhuxze** [comment]
Closing this issue as we don't think this is the right pattern for the RNDS.
