### ISSUE TITLE
Help with CheckCS50. 

### ISSUE THREAD

**Issue by Hau519** [Royal-Navy/design-system#1084]
what cs50 said is not the same as what I checked. Could someone please help me to explain? TIA

### Screenshot
*Add a screensh
![image0](https://user-images.githubusercontent.com/65142251/84337618-03fbbf00-ab68-11ea-83e5-7015a6bd6956.jpeg)
ot*

**Comment by m7kvqbe1** [comment]
It looks like you have posted an issue in the wrong repository.

This issue has now been closed.
