### ISSUE TITLE
(Spike) Optimise CI pipeline

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#1105]
Our current CI pipeline does a fantastic job of testing and safeguarding our code.

Currently, its average running time is between 10-20 minutes. Whilst this isn't overly long for what we're managing to achieve with it, it does fuel the "rebase queue" issue, where multiple PRs take a long time to merge due to the CI tool running.

This ticket is completed when we have reviewed the current CI pipeline and investigated if/how we can improve it.

Initial areas to focus on:
- parallelisation of build tasks
- checking for duplicate tasks*

(*) The Icon Library build task is run in at least two pipelines, often back to back in the same PR - this is definitely a candidate for optimisation.

**Comment by elglup** [comment]
Completed some analysis of current workflows to determine where/if any improvements can be made.

Determined that most jobs are already nicely executed as part of defined Circle workflows.  Parellisation is working well.
Mostly delays seem to be at the Circle end with jobs waiting for resource at certain time but this is not happening too frequently.

Biggest win is a refactor of the icon library build job, this is executed 3 times in the build_and_test_feature & build_test_and deploy_next jobs, and four times in the build_test_and_deploy_latest job.

Have enabled Circle 'Auto-cancel' feature, this will automatically cancel any queued or running builds for a branch when a new build is triggered on that branch

Also will be refactoring publish_next job via #1168 and #1172 exploring consolidation of checkout/dependencies
