### ISSUE TITLE
Add ability for Masthead to have no logo

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#1106]
### Description

At the moment [the Masthead component](https://docs.royalnavy.io/components/masthead) has an optional Logo prop.

However, if no logo is specified, a default logo is used.

It would be good if there was a way to have no logo for services that don't have one. (Also, when there is no logo, the left margin on the service name may need to be reduced or removed.)

(If I've missed something, please let me know.)

**Comment by ghost** [comment]
As recently discussed with the Design System team Product Owner, we don't require applications to have their own logo.

**Comment by jpveooys** [comment]
I should have some time to work on this early next week. Let me know if anyone has any comments or that conflicts with anything.

Something like a `fallBackToDefaultLogo` prop (with a default of `true`) might work (to avoid breaking backwards compatibility as current apps might be relying on the current default logo).
