### ISSUE TITLE
Add ability to configure Masthead nav item padding

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#1110]
### Description

One of our exemplar projects uses icons in `Masthead` nav items (as opposed to the text used in the examples in the docs).

We'd like to reduce the (internal) horizontal padding between nav items as it ends up being a bit much when using icons.

There doesn't seem like an easy way to do this at the moment – perhaps a Sass variable would be useful here? I appreciate this is a fairly specific request, so am open to any other options.

**Comment by hxltrhuxze** [comment]
I'm afraid we won't be offering this level of customisation - please override the CSS classes if you need something specific.
