### ISSUE TITLE
(Spike) Investigate Form Handling

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#1111]
>We are experiencing some really horrible issues with the Formik library (it's not just us). It has serious performance issues with more complex forms (re-renders on every input) amongst design flaws in other areas we've been wrestling with over the last week.
>
>One side effect is some extremely frustrating focus/blur bugs when Formik is used in conjunction with more complex custom form components (DatePicker is an example - we've gone through multiple implementations of the component our end to try and overcome these issues - to no avail).
>
>We'd like to draw your attention to what appears to be the new 'meta' in form land (https://react-hook-form.com/). We'd be very keen to hear from you if you have already had some experience with this library. (edited)

**Comment by m7kvqbe1** [comment]
https://github.com/Royal-Navy/design-system/pull/1687

After some discussion we feel that a HOC isn't the best implementation for decorating fields with errors and creating compatibility with form libraries. 

HOCs are notorious for not playing nice with static types.

We feel hooks might be a better paradigm to leverage.

**Comment by hxltrhuxze** [comment]
Closing in favour #2301
