### ISSUE TITLE
(Spike) Investigate Compound Timeline micro to macro view scaling

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#1129]
We need Timeline views to be able to scale out from day level to year level.

This spike involves investigating potential design constraints, prior art and experimenting with potential technical implementation.

**Comment by asifshaik04** [comment]
Like how there are _TimelineMonths , TimelineWeeks, TimelineDays_  would be nice to have something like _TimelineHour_. It will help in planning things on hourly basis. If there is _hourWidth_ property like how there is _dayWidth_ would be beneficial.

**Comment by flcbmajoka** [comment]
Like how there are _TimelineMonths , TimelineWeeks, TimelineDays_  would be nice to have something like _TimelineHour_. It will help in planning things on hourly basis. If there is _hourWidth_ property like how there is _dayWidth_ would be beneficial.

**Comment by thyhjwb6** [comment]
Spike has been pushed to [`spike/timeline-scaling`](https://github.com/Royal-Navy/design-system/commit/1d80e5d21014391b07c71a416935379c96cd8b30)

Other points worth considering:
- mouse controlled zoom
- click event to zoom
- stay with event when zooming in/out
