### ISSUE TITLE
DatePicker popover is misaligned when displayed below

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#1136]
The popover for the DatePicker is centred on the component but this can cause it to be misaligned due to its width when displaying ranges.

Can we align it with the left of the component when displayed below?

### Screenshot
<img width="999" alt="Screenshot 2020-06-17 at 17 10 16" src="https://user-images.githubusercontent.com/48056118/84922313-94cd2000-b0bd-11ea-9e39-6aaac25f5448.png">

**Comment by m7kvqbe1** [comment]
How about if the tab sits in the middle and the component itself sits directly underneath.

Bad ASCII art:

```
-|------Component-------|-
------------^-------------
----|---DatePicker---|----
```
