### ISSUE TITLE
DatePicker dropdown button doesn't work

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#1137]
### Steps to reproduce
* Create a form with a date picker and set it to isRange=true
* Try and click on the dropdown

### Screenshot
![Jun-17-2020 17-13-07](https://user-images.githubusercontent.com/48056118/84922613-fee5c500-b0bd-11ea-8b79-13cb4dd1e305.gif)

**Comment by m7kvqbe1** [comment]
Quick fix - we will action.
