### ISSUE TITLE
TimelineSide not printing Row name of a customized TimelineRow

### ISSUE THREAD

**Issue by flcbmajoka** [Royal-Navy/design-system#1167]
Having issues with _TimelineSlide_  **It is not printing row name** when we have a customized _TimelineRow_  e.g. _BookingEventRow_

I have code structure something like below

`<Timeline>`
` </TimelineSlide>`
   `<TimlineRows>`
      `<BookingEventRow booking={bookinData/>`
   `</TimlineRows>`
`</Timeline>`

Inside _BookingEventRow_

`<TimelineRow name={bookingData.name}>`
`  <TimelineEvents>`
.....
...
` </TimelineEvents>`
`</TimelineRow>`

or

`<div>`
`<TimelineRow name={bookingData.name}>`
`  <TimelineEvents>`
.....
...
` </TimelineEvents>`
`</TimelineRow>`
`</div>`

or

`<Draggable>`
`<div>`
`<TimelineRow name={bookingData.name}>`
`  <TimelineEvents>`
.....
...
` </TimelineEvents>`
`</TimelineRow>`
`</div>`
`</Draggable>`

When it is rendered, the row name is missing

**Comment by m7kvqbe1** [comment]
We are currently in the process of doing some refactoring that we hope will fix this issue as a side effect https://github.com/Royal-Navy/design-system/issues/938.

**Comment by thyhjwb6** [comment]
@flcbmajoka please confirm this has been fixed in the latest release.

**Comment by thyhjwb6** [comment]
Having taken a closer look I can see this was not fixed in the previous release. [A PR](#1376) will address this issue.
