### ISSUE TITLE
(Spike) Investigate styled-components for React Component Library

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#1170]
Research styled components, and determine if they are the right choice.

- How do we record design tokens?
- How will this affect architecture?

**Comment by aaranmcguire** [comment]
I would love to see this project use styled-components. I've just started a new project using Next.JS using SSG (Server Side Generation) and while I love the component designs of this project I'm not able to use it as it only support client side rendering. Moving over to styled-components would allow it to support SSG & SSR.

**Comment by aaranmcguire** [comment]
@m7kvqbe1 May I ask what the result of the investigation was?

**Comment by m7kvqbe1** [comment]
> @m7kvqbe1 May I ask what the result of the investigation was?

We are indeed going to be migrating away from SASS in favour of styled-components.

We have created a ticket for the creation of a `@royalnavy/design-tokens` package (see https://github.com/Royal-Navy/design-system/issues/1331). 

This package will in turn be consumed by the existing css-framework and the newly migrated 'styled' components themselves - allowing us to progressively migrate components one at a time.

This work stream will be actioned soon.
