### ISSUE TITLE
(Spike) Investigate Standardising Form component styles

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#1178]
# Overview

The form components in the Royal Navy Design System (RNDS) are some of the oldest components within the DS. Having been designed and built over a 2 year period, their design and behaviour has started to deviate from one another.

This Spike is to investigate the current RNDS form landscape and review the existing components. It should also check industry best practices, including approaches to form layout and error handling.

## Existing form components (storybook links)
- [Number Input](https://storybook.royalnavy.io/?path=/story/number-input--default)
- [Text Input](https://storybook.royalnavy.io/?path=/story/textinput--vanilla)
- [Textarea](https://storybook.royalnavy.io/?path=/story/textarea--vanilla)
- [Radio Button](https://storybook.royalnavy.io/?path=/story/radio--vanilla)
- [Radio Button Enhanced](https://storybook.royalnavy.io/?path=/story/radioenhanced--default)
- [Checkbox](https://storybook.royalnavy.io/?path=/story/checkbox--vanilla)
- [Checkbox Enhanced](https://storybook.royalnavy.io/?path=/story/checkboxenhanced--default)
- [Select](https://storybook.royalnavy.io/?path=/story/select--default)

### Additional (related) components
These components, whilst not strictly "form" components are regularly used in a form context, so should be included as part of this investigation.

- [Switch](https://storybook.royalnavy.io/?path=/story/switch--vanilla)
- [Range Slider](https://storybook.royalnavy.io/?path=/story/rangeslider--vanilla)

## To Investigate
- The current RNDS form landscape
- How the RNDS can improve the look and feel of the components to increase consistency
- How the RNDS forms should handle error messaging
- Best practices for form layout and flow

## Definition of Done

This ticket should be considered complete once the above items have been investigated and a plan to rejuvenate RNDS forms has been decided on.

**Comment by k9dh3zij** [comment]
Twenty components have been identified, although some will eventually be merged into wider categories.

An initial set of context, notes, design and functionality considerations has been captured for each. 

Further notes relating to form layout, alignment and best practice have been captured.

Four new tickets have been created in order to take this work forward, so I'm now closing this.

#1735 
#1734 
#1733 
#1732
