### ISSUE TITLE
Ability to group multiple TimelineRows into one

### ISSUE THREAD

**Issue by flcbmajoka** [Royal-Navy/design-system#1197]
### Description

Would be nice to have an ability to group multiple TimelineRows into one Row with common Row name

Alongside  TimelineRow there is a need for something like AdvancedTimelineRow. Please see below sample wireframe for this

![advancedTimelineRow__1](https://user-images.githubusercontent.com/66831714/86600090-7741f680-bf97-11ea-9ad9-585f18bc5b74.jpg)

**Comment by m7kvqbe1** [comment]
In order to achieve this you should be following the example composition detailed here:

https://docs.royalnavy.io/timeline/#advanced-custom-layouts
https://github.com/m7kvqbe1/fp-grey-box

The out of the box `TimelineSide` component should only be used for simple single row layouts.

I have closed this ticket for now.

**Comment by m7kvqbe1** [comment]
@flcbmajoka

**Comment by flcbmajoka** [comment]
I have already tried your suggestion. The sample project has got a compile error at renderColumns at lines like [this](https://github.com/m7kvqbe1/fp-grey-box/blob/master/src/App.tsx#L92). Somehow I did some workarounds to avoid it then when I eventually launch the application I got to see a different screen, not what it is shown in this [link](https://docs.royalnavy.io/timeline/#advanced-custom-layouts). Please see the attached screenshot of it

Please see the attached screenshots of the error message and the web page I get to see.

![advancedRow](https://user-images.githubusercontent.com/66831714/88294171-d7ed6500-ccf3-11ea-8e51-e9a6fc051d76.jpeg)

![errorMessage](https://user-images.githubusercontent.com/66831714/88294144-cefc9380-ccf3-11ea-96b3-25f14580f539.jpeg)

Please let me know your thoughts and correct me if I am missing something.

**Comment by m7kvqbe1** [comment]
The version you see is correct - the example in the documentation has had some additional styles added.

The `fp-grey-box` example is there as a barebones example to illustrate the pattern.

The compile error could be quickly fixed by declaring the required arguments for that anonymous function.
