### ISSUE TITLE
Lazyloading in Timeline component

### ISSUE THREAD

**Issue by flcbmajoka** [Royal-Navy/design-system#1251]
### Lazyloading 
_Timeline_ component for planning events in a Gant chart view serves the purpose. But ss the planner gets busy and when we need to plan over the years and load with 5 to 10 years worth of data then there are performance issues.

- Introducing Lazyloading concept would be very beneficial in the Timeline component in terms of performance and user experience. 

- In the given 5 year view if the user is viewing only 4 months at one point then we should only load data for those 4 months instead of whole data. As the user navigates to the next set of 4 months then that next set of data should be loaded

**Comment by m7kvqbe1** [comment]
We believe this is something that should be handled in the data layer of your application.

We'd be happy to consider ways in which we might be able to make this easier for you but at this stage it's something the library has no opinion on.

@flcbmajoka
