### ISSUE TITLE
Number Input only calls onChange when component it blurred

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#1256]
### Steps to reproduce
Create a form with a number input
Add an onChange handler function that gets the value change and uses it to update it's forms state
Display the form state on the screen

When the user changes a number by editing the value, not the buttons, the onChange is not called until the field looses focus.

In previous versions of the toolkit the onChange was called for all changes and appears to have changed here:

https://github.com/Royal-Navy/design-system/commit/99143995d78f52595cc58e06ff989636e7f36f70

**Comment by thyhjwb6** [comment]
`onChange(event)` appears to be missing on [this line](https://github.com/Royal-Navy/design-system/blob/01d8d8834dd23e2fbc5d482ebf67cfcdf7f0bf10/packages/react-component-library/src/components/NumberInput/NumberInput.tsx#L106).
