### ISSUE TITLE
DatePicker down arrow button is a submit button

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#1260]
### Steps to reproduce

1. Render e.g.

```jsx
<form onSubmit={(e) => {alert('😱️'); e.preventDefault()}}>
  <DatePicker
    startDate={new Date('11/01/2018')}
  />
</form>
```
2. Click on the date picker down arrow

The form is unexpectedly submitted.

### Screenshot

![date-picker](https://user-images.githubusercontent.com/66470099/88185182-8bd6ed80-cc2b-11ea-956e-fda196e53bab.gif)

**Comment by m7kvqbe1** [comment]
Looks like we need to stop the event bubbling up to the form - will fix.

**Comment by jpveooys** [comment]
Adding `type="button"` might be enough – unfortunately `submit` is the default (in a form)...
