### ISSUE TITLE
Runtime issues with TimelineSide of the Timeline component

### ISSUE THREAD

**Issue by flcbmajoka** [Royal-Navy/design-system#1270]
### Steps to reproduce
Hello team. I am having some runtime issue with _TimelineSide_ of Timeline component. Due to this error application is NOT launching on our VM(dockerised) environment. It shows as a blank white screen.  I have got simple empty TimelineSide as 

`<TimelineSide/>`

If I comment out or delete the above line then the application works but without the _TimelineSide_.  I am using pretty latest version **2.11.0**. Please see the screenshot of the console error message

### Screenshot
*_TimelineSide_ console error message*
![timelineslideError](https://user-images.githubusercontent.com/66831714/88538447-4b021e80-d007-11ea-9a66-efc16a1349f5.jpeg)

**Comment by thyhjwb6** [comment]
Discussed with @flcbmajoka and this is not a regression in `2.11.0`

There was previous work to ensure unique keys. Maybe something was missed.

**Comment by flcbmajoka** [comment]
Yes, even I think it is an issue with keys.  I had some keys missing on my _TimelineEvents_  of `TimelineRow` after adding tose keys I could now at least see the page with _Timeline_ component(without _TimelineSide_)

**Comment by el7h1rw2** [comment]
Should be fixed as a byproduct of the work currently being done.

**Comment by m7kvqbe1** [comment]
We are currently in the process of doing some refactoring that we hope will fix this issue as a side effect https://github.com/Royal-Navy/design-system/issues/938.

**Comment by thyhjwb6** [comment]
@flcbmajoka please confirm this has been fixed in the latest release.

**Comment by thyhjwb6** [comment]
Having tested this with the latest version, this is now fixed.
