### ISSUE TITLE
Text-Input does not have errorMessage prop as per docs

### ISSUE THREAD

**Issue by stonefarmer9** [Royal-Navy/design-system#1285]
The Text-input component is shown in docs to have an errorMessage prop but it is not present in the components props lists.

**Comment by m7kvqbe1** [comment]
The error message is displayed by using the component in combination with a form handling library called Formik (https://github.com/formium/formik).

There is a HOC (https://reactjs.org/docs/higher-order-components.html) that allows form components to be enhanced to display Formik validation error messages. 

The source for this enhancer can be seen here: https://github.com/Royal-Navy/design-system/blob/master/packages/react-component-library/src/enhancers/withFormik.tsx

I have closed this ticket for now but feel free to reply if you require further assistance - alternatively you might want to start a discussion around form handling methods / techniques in our new discussion section (https://github.com/Royal-Navy/design-system/discussions).

**Comment by m7kvqbe1** [comment]
It's worth also noting that there are other notable form handling libraries such as React Hook Form (https://react-hook-form.com/).
