### ISSUE TITLE
Badge colours in code do not match the designs

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#1335]
The colours for the badge components do not match the designs. If you take a look at the documentation site you can see this.

<img width="828" alt="Screenshot 2020-08-11 at 13 49 03" src="https://user-images.githubusercontent.com/48056118/89899087-a6243b80-dbd9-11ea-8262-3b818d6d44f4.png">

**Comment by hxltrhuxze** [comment]
@antictor We updated the badges to ensure they pass WCAG A11Y guidelines. The Sketch file and React components have parity - the examples on the docs site have unfortunately fallen behind.
