### ISSUE TITLE
Breadcrumb Styling - Last breadcrumb misaligned from the preceding breadcrumbs

### ISSUE THREAD

**Issue by jk68mnpo** [Royal-Navy/design-system#1338]
### Description
Using v2.12.0 for all design team packages

- rn_breadcrumbs__title is slightly misaligned with the preceding breadcrumbs

### Code Snippet
```
<Breadcrumbs>
  <BreadcrumbItem link={<Link to="/">Home</Link>} />
  <BreadcrumbItem link={<Link to="/new-page">New Page</Link>} />
</Breadcrumbs>
```

### Environment
- Chrome 69
- Firefox 77.0.1

**Comment by m7kvqbe1** [comment]
I have just tested this in browserstack chrome 69 and I was unable to reproduce - are you using the correct font stack?

Please could you provide us with a screenshot.

Many thanks!
