### ISSUE TITLE
Start date difficult to change in range DatePicker once dates selected

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#1391]
### Steps to reproduce

1. Go to https://storybook.royalnavy.io/?path=/story/datepicker-examples--formik
2. Try to change the start date

It's quite difficult, it only really lets you extend the date range. (I think this is a recent regression.)

### Demo

![date-picker-start-date](https://user-images.githubusercontent.com/66470099/91834253-aeebb880-ec3f-11ea-8db3-87351aabfbf2.gif)

**Comment by m7kvqbe1** [comment]
This is actually the desired UX now that we have changed the underlying implementation:

https://react-day-picker.js.org/examples/selected-range

If you click multiple times on the start date you should be able to change it.

I've closed this ticket for now. We welcome to suggestions for UX improvements.

**Comment by jpveooys** [comment]
The use case is more like the 'Works with input fields' on the home page: http://react-day-picker.js.org/

That doesn't behave in the manner described; it is always start date followed by end date.

**Comment by ghost** [comment]
I think the behaviour around changing the start date of the range is odd - I've not seen an implementation where you have to double click to change the start date. A more usual way of doing it surely is with a single click like this http://www.daterangepicker.com/
