### ISSUE TITLE
Introduce prop to change colour of Timeline Event and hide overflow of week dates

### ISSUE THREAD

**Issue by kixdcrwtkqgiyrxs** [Royal-Navy/design-system#1424]
### Description
- For TimelineEvent component, introduce new prop to allow a colour change for different types if event - rather than having to use a custom render
- In TimelineWeeks -> class: timeline__week, set overflow:hidden (or equivalent), so that there isn't overhang of the week date

**Comment by thyhjwb6** [comment]
> In TimelineWeeks -> class: timeline__week, set overflow:hidden (or equivalent), so that there isn't overhang of the week date

Can you send a screenshot of what this point is trying to address?

**Comment by kixdcrwtkqgiyrxs** [comment]
It'd when you use longer date formats. Just something to consider - not a necessary fix :)

![image](https://user-images.githubusercontent.com/71075246/94702212-66eead00-0335-11eb-9da8-edc7ceba9168.png)

![image](https://user-images.githubusercontent.com/71075246/94702443-ab7a4880-0335-11eb-8493-224e7a0909bd.png)

**Comment by thyhjwb6** [comment]
Thank you @kixdcrwtkqgiyrxs I have created a new issue for the overlap #1499.
