### ISSUE TITLE
Implement Tooltip on click and mouseover behaviours

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#1459]
Add functionality to the popover and the tooltip so they can be toggled via click and then dismissed by clicking off of them. This should be optional behaviour for the time being.

The hover interaction has been highlighted as potentially causing problems in certain environments.

**Comment by ghost** [comment]
Would it be worth considering an 'X' close icon in addition to the 'click outside' function?

**Comment by hxltrhuxze** [comment]
@aavvjg6j good point, however I do wonder if having the close button implies you _have_ to click it. Given that it's a small target (and our above context), it might be bad to encourage this learned behaviour.

Happy to add it in if the research disagrees with my statement.

**Comment by thyhjwb6** [comment]
This is on hold whilst the nuances of this component are investigated further.

**Comment by hxltrhuxze** [comment]
Closing as our recommendation is to use the [Popover](https://docs.royalnavy.io/components/popover/) component
