### ISSUE TITLE
Long week text overlaps at end of Timeline

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#1499]
Split out from #1424.

#### Storybook reproduction
```
export const LongTextRepro = () => {
  const CustomTimelineWeek = (
    index: number,
    isOddNumber: boolean,
    offsetPx: string,
    widthPx: string,
  ) => {
    return (
      <span
        style={{
          display: 'inline-block',
          marginLeft: offsetPx,
          width: widthPx,
          height: '2.5rem',
          paddingLeft: '.5rem',
        }}
      >
        something a little longer
      </span>
    )
  }

  return (
    <Timeline startDate={new Date(2020, 3, 1)} today={new Date(2020, 3, 15)}>
      <TimelineSide />
      <TimelineTodayMarker />
      <TimelineMonths />
      <TimelineWeeks render={CustomTimelineWeek} />
      <TimelineDays />
      <TimelineRows>{}</TimelineRows>
    </Timeline>
  )
}
LongTextRepro.storyName = 'LongTextRepro'
```

When you browse to the end, there is overlap.

### Screenshot
<img width="1141" alt="Screenshot 2020-10-02 at 11 57 54" src="https://user-images.githubusercontent.com/56078793/94916392-848f5400-04a6-11eb-812b-6c6ad117184f.png">

**Comment by m7kvqbe1** [comment]
This appears to be because the custom timeline week component (to which styles are devolved) is missing the following styles:

```css
white-space: 'nowrap';
overflow: 'hidden';
```

<img width="1509" alt="Screenshot 2020-11-12 at 14 24 06" src="https://user-images.githubusercontent.com/48086589/98952026-e229ae00-24f2-11eb-9f1c-1b9870154f9b.png">

**Comment by thyhjwb6** [comment]
Cool 👍 

When raising this issue I was running with the assumption that each custom render of a week was being rendered inside something which needed the styles updating but I can see what is happening now.
