### ISSUE TITLE
RangeSlider: Add support for custom value formatter

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#1561]
### Background

In the range slider in our exemplar project the primary unit of the slider is percentages, with steps of 1%. This implies a domain of [0, 100] and step of 1.

However, we also need to show a secondary label showing the value the percentage is equivalent to. Currently, to get this to display, it seems we need to use a domain representing the secondary value (e.g. [0, 954]) and convert from and to percentages in the client app. This has a few undesirable side effects, for example the ticks snap to round values in the domain (e.g. 0, 100, 200), instead of the desired 0%, 10%, 20% etc.

### Proposed solution

My proposal is to add a new optional prop to the component, named e.g. `valueFormatter`, that takes a function with a signature of roughly `(value: number, percentage: number, displayUnit: string) => string`. The function would return the string to display and would be called here:

https://github.com/Royal-Navy/design-system/blob/99229de27392dce7446dc6158259f0570ba16b5c/packages/react-component-library/src/components/RangeSlider/Handle.tsx#L44

This would enable the domain to be kept to [0, 100] with a step of 1 in our exemplar app but still display the secondary value the percentage represents (with `hasPercentage` being used to also show the percentage).

(If I've missed anything let me know.)

**Comment by thyhjwb6** [comment]
A couple of thoughts:
- would a prop bag work better for the function parameters? This is something we would like to change in `Timeline`
- would the prop name for the function be more consistent if it was prefixed with `render`?

**Comment by jpveooys** [comment]
> would a prop bag work better for the function parameters? This is something we would like to change in Timeline

As in a typed object? That would work well, yep.

> would the prop name for the function be more consistent if it was prefixed with render?

I think `render` would imply it returns a ReactNode while this is only intended to format the text at the moment. The text ends up in the `data-value` attribute so it can only be a string at present.

It could be named `formatValue` rather than `valueFormatter` if that is more consistent, though.
