### ISSUE TITLE
Text-area hint text doesn't disappear and overlaps free text

### ISSUE THREAD

**Issue by bo7909** [Royal-Navy/design-system#1588]
Text-area fields within this library https://www.npmjs.com/package/@royalnavy/react-component-library do not remove hint text once user starts typing and hint text overlaps user input text making the text obscured.
<img width="1156" alt="Screenshot 2020-10-20 at 19 58 44" src="https://user-images.githubusercontent.com/73170334/96631937-e48f5280-130e-11eb-9638-8ccb9aa979a2.png">

**Comment by thyhjwb6** [comment]
This was [fixed](https://github.com/Royal-Navy/design-system/commit/2b2b9043f8fc779357992a945310fc4d280cfaff#diff-8d2b8ca1e5e4c50a102045afc7f8319839a7e8fbdbf17e8c1389a876047ae8e9) and will be available in `2.16.0`.
