### ISSUE TITLE
(Spike) Investigate styled-components conventions in other libraries

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#1602]

**Comment by m7kvqbe1** [comment]
## Take homes

- Get much better at breaking up components - consider creating a 'partials' directory.

- Props unique to the styled-component that do not need to be drilled to the wrapped component / markup should be marked as transient ($). Transient by default (think const).

- Avoid targeting markup even if it's namespaced by parent styled-component. This is sometimes a smell that the component needs breaking up further. There are exceptions to the rule - consider on a case by case basis.

- Avoid mixing classes / BEM and styled-components. Stick to the single paradigm.

- Avoid setting the style prop and instead pass props to the styled-component. Identify discrete UI states (avoiding one-to-one relationship between props and CSS properties where possible).

- Always use the css`` tagged template literal.

- Always declare components outside of the React component (performance - CSS class re-generation).

- It is important the className prop is attached to a component's parent DOM node. Not doing so will break `const newcompo = styled(Component)` HOC usage.

- Specificity trick: https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity

- It would be nice to improve upon the breakpoint getter in the design-tokens package. See this for prior art: https://github.com/jameslnewell/styled-components-breakpoint

## Noteworthy resources

https://styled-components.com/

https://styled-components.com/ecosystem

https://pagepro.co/blog/moving-best-scss-practices-to-styled-components-part-1/

https://itnext.io/thinking-in-styled-components-e230ea37c52c
