### ISSUE TITLE
Pagination component only showing 1 page on 1st render

### ISSUE THREAD

**Issue by bo7909** [Royal-Navy/design-system#1616]
On first render, there is only 1 page shown, even if the results have more than 1 page available. You have to press next to then see all the other pages.

**Comment by m7kvqbe1** [comment]
Please could you create a minimal reproduction for this issue.

**Comment by m7kvqbe1** [comment]
I have closed this ticket for now - please feel free to provide a minimal reproduction and we will re-open it.
