### ISSUE TITLE
New Sidebar issues

### ISSUE THREAD

**Issue by kixdcrwtkqgiyrxs** [Royal-Navy/design-system#1623]
1. 'View Profile' on the Sidebar User should be optional
2. Logout button on Sudebar User doesn't do anything/no option to pass prop yo do something
3. All content is pushed off the page, 'aside' should have absolute positioning and an increased z-index
4. Icons are no longer usableand 'graph' icon is missing from the library

**Comment by m7kvqbe1** [comment]
@kixdcrwtkqgiyrxs 

- re: 1 - We will action this.

- re: 2 - We will action this - I assume you mean the Logout button in the expanded state?

- re: 3 - Are you using the `SidebarWrapperE` layout companion component - opening the sidebar should shift the content pain to the right as opposed to the Sidebar floating above the app. See spec here (https://github.com/Royal-Navy/design-system/issues/965): "A wrapper to surround the main application, allowing the main app content to resize when the sidebar is expanded and contracted".

- re: 4 - Icons used by the previous Sidebar are now deprecated. Icons from the `@royalnavy/icon-library` package should be used instead. You can browse the full collection [here](https://material.io/resources/icons/?style=round).

**Comment by kixdcrwtkqgiyrxs** [comment]
1. thanks :)
2. yep, expanded
3. I tried that yesterday and still got the issue, i'm now getting babel errors when i try and add it though 🙃
4. Ok cool, thanks :)
