### ISSUE TITLE
(Spike) Investigate Timeline Drag & Drop

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#1658]

**Comment by thyhjwb6** [comment]
[Spike has been done on a branch](https://github.com/Royal-Navy/design-system/tree/spike/timeline-drag-drop). Note that this code will need more thinking when it comes to properly integrating it.

## Basic idea
- Have knowledge of all X and Y coordinates
- Use `react-dnd`
- Use single drop zone
- When event is dropped, calculate new coordinates
- Continue to use event offset

## Notes
- Moving between rows was not covered but some ideas:
1. A drop zone per row
2. Detect the drop and literally move the element from the row to another row
- Performance was investigated. Even without drag and drop, once we get to 2000 events there are performance concerns
- We can introduce hover states or "ghost blocks" to exist with UX

## Other ideas
- Use `alt` to duplicate event
- Overlapping blocks, how they are presented
- Consideration needs to be given to events that are outside of the range
- Event custom render has not been tested
- Test with all browsers
- Continue thinking about performance
