### ISSUE TITLE
Docs: Fix Forms subsection in the navigation

### ISSUE THREAD

**Issue by k9dh3zij** [Royal-Navy/design-system#1738]
For some reason only 4 options appear under the Forms subsection. From our devs:

Looks like that might be a bug in the menu generation - I can see checkbox exists but it hasn't been nested underneath Forms in the menu. The URL structure of that page is correct though.

![image](https://user-images.githubusercontent.com/73531035/100743896-dab04300-33d4-11eb-8050-c3395baefcb6.png)

**Comment by el7h1rw2** [comment]
This will be addressed with the new Docs site.
