### ISSUE TITLE
Icons - export the Filter_Alt icon 

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#1788]
### Description
https://material.io/resources/icons/?search=filter&icon=filter_alt&style=baseline

We wish to use this icon, as the current fliter icon exported does not fit the purpose of filtering a table as it related to imagery.

**Comment by m7kvqbe1** [comment]
It looks as though this is one of numerous additional icons that have recently been added to the library by Google.

We are looking at bringing these new icons across into our own library.

I believe there is a batch script the designers need to first run on the source assets.
