### ISSUE TITLE
(Spike) Investigate monitoring tools

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#1871]
As an outcome from the DevOps workshop in 2020.  Missing in the DevOps process is continuous improvement, which relies on monitoring.

**Goals**:

- Monitoring the availability of service elements we support
- Access to our service elements (e.g. website hits, downloads)

**Acceptance Criteria**:

- [ ] Discussion and agreement on the data points we want to monitor, along with tooling suggestions
- [ ] Summary report is created and shared with stakeholders
- [ ] (If needed) Stakeholder approval of any spend
- [ ] Issues created to instantiate the monitoring tools

**Comment by elglup** [comment]
- [x] Discussion and agreement on the data points we want to monitor, along with tooling suggestions
- [x] Summary report is created and shared with stakeholders
- [x] (If needed) Stakeholder approval of any spend
- [x] Issues created to instantiate the monitoring tools
