### ISSUE TITLE
DatePicker: The ability for users to type the date

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#1904]
### Description
Currently the date picker does not allow users to type a date in. It would be useful for users who have to select dates 2/3 years in advance which could be 24/36 clicks away at the moment. 

Would this be possible for power users?

**Comment by k9dh3zij** [comment]
Spec discussed:

- Add a dd/mm/yyyy regex mask on to the Date Picker input field
- Investigate if possible to display __ / __ / ____ ghost text in input field as user is typing a date

**Success scenario**

- User clicks on input (masked input is now focussed)
- Calendar widget opens
- User manipulates date via input (resulting in valid date)
- Calendar widget updates accordingly
- Component loses focus, calendar widget closes


**Fail scenario**

- User clicks on input (masked input is now focussed)
- Calendar widget opens
- User manipulates date via input (resulting in an invalid date)
- Calendar widget reverts to a null state (same as when no date has been entered yet).
- The input's visual error state is displayed
- Component loses focus, calendar widget closes - the erroneous / incomplete value remains in the input and the input is still in its error state
- If the user attempts to submit the form the error state persists and the form cannot be submitted until the date is corrected
