### ISSUE TITLE
TabSet - Full width tab set

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#1907]
### Description
We currently override css classes associated with the TabSet component in order to achieve a scrollable two tab full width set.

This is our css overrides
```
.rn-tab-set {
  height: 100%;
}

.rn-tab-set__head {
  // fix for older browsers
  min-height: 64px;
}

.rn-tab-set__body {
  height: 100%;
  padding: 1.5rem 0 !important;
  overflow-y: auto;
}

.rn-tab-set__tab-item {
  width: 50%;
}

.rn-tab-set__tab {
  width: 100%;

  &.is-active {
    background-color: color('neutral', '400');
    border-color: color('neutral', '200');
    color: #fff !important;
  }
}
```

This custom css is to allow us to achieve two tab buttons that are both 50% width each and with a scrollable tab body. We have also overriden the color for the is-active however we do not expect this to be done to the design system too, however would like the .is-active class to exist beyond the styled components migration if possible so we can continue to do this ourselves.

The react code that we use is as follows:
```
<TabSet>
  <Tab title="title 1">
    <Our own custom component />
  </Tab>
  <Tab title="title 2">
    <Our own custom component />
  </Tab>
</TabSet>
```

Could a simple change or addition to the TabSet component be made that allows the number of Tabs within it to be 100%/x width and with a tab body that is scrollable please.

**Comment by thyhjwb6** [comment]
The `is-active` class will not be exposed but implementing the desired result will be achieved with code similar to:

```
const StyledTabSet = styled(TabSet)`
  ${StyledTabProps} {
    ${({ $isActive }) => $isActive && css`
      // here
    `}
  }
`
```
