### ISSUE TITLE
Select - no margin given to select component

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#1908]
The Select component (https://github.com/Royal-Navy/design-system/blob/master/packages/react-component-library/src/components/Select/Select.tsx) does not have the same margin as the DatePicker or NumberInput, this results in if two Select component are on top of each other they do not have a margin. We have resorted to doing the following overrides:

`.rn-select__control {
  margin: spacing('6') 0;
}`

But this is relying on implementation detail.

**We should either make all form components have no margin or the same margin so it is either up to the developers to structure their forms with equal margin/spacing between inputs or have it up to the inputs themselves to define their margins.**

Examples of margin on other Form components:
https://github.com/Royal-Navy/design-system/blob/master/packages/react-component-library/src/components/NumberInput/NumberInput.tsx
https://github.com/Royal-Navy/design-system/blob/master/packages/react-component-library/src/components/DatePicker/DatePicker.tsx

**Comment by m7kvqbe1** [comment]
Related issue: https://github.com/Royal-Navy/design-system/issues/1880

**Comment by m7kvqbe1** [comment]
This ticket has been marked as v3 and will be addressed as part of the next major release. 

There are breaking changes associated with these works.

**Comment by m7kvqbe1** [comment]
For now please continue to override that CSS class.

We've closed this ticket as this inconsistency will be addressed by the upcoming v3 forms work.
