### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#192]
There is a requirement to provide a select component within an application.

The select will act like a regular form Select component, though allows the developer to specify both regular text content or html content.

The code for a select should specify a list of options, each one specifying a value and a text label or children. The current value and field name must be provided to and when a value changes it called onChange with a regular field change type event.

Finally the component must work as a Formik component.

Below are examples of use, note the version to select fleet and how the badge is aligned.

<img width="145" alt="Screenshot 2019-08-02 at 15 42 46" src="https://user-images.githubusercontent.com/48056118/62378351-8d9c3280-b53c-11e9-88ba-40b15dcfae5f.png">
<img width="226" alt="Screenshot 2019-08-02 at 15 41 19" src="https://user-images.githubusercontent.com/48056118/62378352-8e34c900-b53c-11e9-8310-0cbd01ac1625.png">
<img width="399" alt="Screenshot 2019-08-02 at 15 41 11" src="https://user-images.githubusercontent.com/48056118/62378353-8e34c900-b53c-11e9-824c-6493b1212774.png">
<img width="345" alt="Screenshot 2019-08-02 at 15 41 03" src="https://user-images.githubusercontent.com/48056118/62378354-8e34c900-b53c-11e9-8a19-cbbf0621b993.png">

**Comment by hxltrhuxze** [comment]
# The custom Select component

The custom Select component is a turbo-charged version of the native `<select>` input. Instead  of relying on the browser to handle displaying the `<option>`'s, this Select displays a custom sheet that can be enhanced with additional components.

[Download Sketch File](https://github.com/Royal-Navy/standards-toolkit/files/3479020/CustomSelect.zip)

## Component States

The Select has eight variations, depending where it currently is in its lifecycle:

- To begin, the Select looks like a regular input, with the label at full height.
- Hovering on the Select will add a 2px blue (`0` spread) `box-shadow` to the input.
- Clicking on the Select will expand the list:
    - Firstly, the Select container will animate to a height of 5 items (or less). Anything else will be hidden behind a scroll.
    - Each Item will then fade in, from top to bottom.
- Hovering on any of the Items will add a light grey background to it.
- Clicking on any item will cause the container to collapse back to its original height, with the new selected item displaying.
![Inputs](https://user-images.githubusercontent.com/48090803/62649897-91b9bd00-b94d-11e9-8fd1-f6a827cc4c9a.jpg)

When an item has been selected, the Select works much the same, except now:
- The Select label is now small and showing the previously selected value
- When the list is expanded, the currently selected item will have a blue background in the list.

![Inputs2](https://user-images.githubusercontent.com/48090803/62649899-91b9bd00-b94d-11e9-9905-b9561a5d8f4d.jpg)

### Scrolling
If a Select contains over 5 items, then scrolling should be added. When a user scrolls the list, a subtle shadow is added to the main area of the Select, causing the items to disappear under it.

<img width="663" alt="Screenshot 2019-08-07 at 20 26 46" src="https://user-images.githubusercontent.com/48090803/62651825-c3cd1e00-b951-11e9-8056-2b08e43d9e6e.png">


---

### Notes
- I think we'll need to discuss the different types of content that will be required for the custom Select. The Select has been sized according to inputs, allowing them to sit flush with one another in a form based layout - this gives us a good approximation of the size that the additional content should be. Overloading a custom Select with a lot of content feels like it would be overly cumbersome for the user to interact with, and may be better served via the (proposed in JIRA) Carousel component.

### Changes from the original design
- Reduced the overall size of the badges to ensure they aren't increasing the height of the selects to be larger than their input counterparts.
- Fixed the alignment of the badge with the text label.
- Removed the horizontal dividing lines between each item.
- Added a Hover & Active states to the Select.
- Added an Active state to the already selected item.
- Added a Hover state to the items.

**Comment by antictor** [comment]
Any chance of a Sketch file to go with this or something we can inspect?

**Comment by hxltrhuxze** [comment]
I've exported the component into its own Sketch file to keep it temporarily separate from the main Standards Toolkit file:

[CustomSelect.zip](https://github.com/Royal-Navy/standards-toolkit/files/3479020/CustomSelect.zip)

**Comment by 09txzS1qs** [comment]
I agree the component shouldn't be over used but think the custom select is a big improvement on default select, especially having the Blue Highlight in the Active with selection and Hover with selection states. Is there any reason for not having one select component with all of the features of the custom select?

**Comment by m7kvqbe1** [comment]
@hxltrhuxze 

It seems a little strange to me how the active and hover highlights overlay the scrollbar.

**Comment by hxltrhuxze** [comment]
@m7kvqbe1 Yeah it's a fair point - I was following OSX standards of having scrollbars appear on scroll. If we're having permanent scroll bars, then I agree we should move the highlight so it isn't clipping.

On the subject of scrollbars though, will we get stuck with the native behaviour? Checking the [Can I Use](https://caniuse.com/#search=scrollbar) support for styling scrollbars and it's still behind flags/not supported in the lowest browser we need to support

**Comment by antictor** [comment]
Can we avoid overriding the browsers rendering of scroll bars and just set it to that the scroll is generated by the browser/os if it's needed or not at all if not

**Comment by antictor** [comment]
I have a work in progress version of this in a project. Once we have the design signed off I'll complete it and get it into the common library

**Comment by 09txzS1qs** [comment]
looks good from a design perspective.

**Comment by antictor** [comment]
Done some investigation and thinking back to how I've used Select components before. The existing design documented above doesn't take into consideration the requirement to be able to type into a select field and get an autocomplete like experience. This is important for some applications that have a long list of options or people who need to use the keyboard for navigation.

Add to this there are some times when the option list needs to be fetched from the server as the user types if there are many many options. Finally the lookup of options as the user types needs to allow for custom filtering logic in case the information displayed contains other information in it too that should not be considered in the regular filtering. Will investigate using a 3rd party component for this and customising it for use in the component kit and ensure it works with Formik as selects and autocomplete components can be alot of hard work.
