### ISSUE TITLE
Number field component

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#193]
A number field needs to be a new component that acts like a regular TextInput component, but only accepts number and has arrows to allow the user to increase and decrease the number by a pre-defined amount.

The field should also allow a minimum and maximum amount to be specified.

What is unclear is how the field should behave when the user tries to clear it.

The field needs to be able to work with Formik.

<img width="123" alt="Screenshot 2019-08-02 at 16 30 38" src="https://user-images.githubusercontent.com/48056118/62381210-e242ac00-b542-11e9-8cea-9c5d292ed725.png">

**Comment by hxltrhuxze** [comment]
Closing in favour of #208
