### ISSUE TITLE
Remove legacy icons from component library

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#1932]
A number of icons need removing from the component library:

- [x] `Bell`
- [x] `Graph`
- [x] `House`
- [x] `Logo`
- [x] `Right-Arrow`
- [x] `Search`
- [x] `Tools`
- [x] `Visibility`
- [x] `VisibilityOff`

## Notes
- Be aware of `rn-iconfill` and changes to styled-components

**Comment by m7kvqbe1** [comment]
This has been marked with v3 as it's a break change.

**Comment by thyhjwb6** [comment]
This will go away once the old `Sidebar` has been removed.
