### ISSUE TITLE
Switch component

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#194]
The switch component is a form component used to record a selection from a number of values. With regards to behaviour, a switch can be thought of like a radio field, allowing a single choice from a small number of options. The different between a switch and radio is presentation, a switch looks similar to a button group.

<img width="101" alt="Screenshot 2019-08-02 at 16 32 33" src="https://user-images.githubusercontent.com/48056118/62381544-a3f9bc80-b543-11e9-9ff3-bc5d8f18b789.png">

A switch should use markup for a field group, complete with legend to act as the label for the range of options.

The switch will need to be compatible with Formik.

Not sure how a switch should present on mobile, this depends how inputs should size. Should they go full width?

**Comment by hxltrhuxze** [comment]
# The Switch Component

The Switch component has 3 states - unselected, hovered, and selected.
- By default, there is always one item that has the selected state.
- Hovering on an item will add a small blue border to it.
- Clicking it will deselect the currently active item and add the Selected state to the item clicked.

<img width="833" alt="Screenshot 2019-08-08 at 16 20 30" src="https://user-images.githubusercontent.com/48090803/62773830-1c5c0280-ba9b-11e9-9981-d2e31d78b7ac.png">

### Mobile

As we have limited screen real estate on mobile, changing the Switch to a Select seems most appropriate here. Vertically stacking the selection could be one option, however this will take up a significant amount of room. 

<img width="772" alt="Screenshot 2019-08-08 at 16 24 11" src="https://user-images.githubusercontent.com/48090803/62773831-1c5c0280-ba9b-11e9-9a4f-12562002e382.png">

---

### Changes from original design
- Changed the overall style of the Switch to distance itself from a button group/button. As these have different effects for the user, we want to keep them visually separate.

**Comment by 09txzS1qs** [comment]
The difference between Hover and Selected is quite subtle in terms of border width. I wonder if the hover could be lower contrast and the selected could have a slightly larger border and higher contrast?

**Comment by m7kvqbe1** [comment]
This is now in active development.

**Comment by m7kvqbe1** [comment]
WIP @ https://github.com/Royal-Navy/standards-toolkit/pull/266
