### ISSUE TITLE
DIalog/Modal component

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#197]
A Modal/Dialog to display a header section, main content and a footer with navigation buttons.

<img width="467" alt="Screenshot 2019-08-05 at 13 06 48" src="https://user-images.githubusercontent.com/48056118/62463581-48694200-b782-11e9-8285-fca28ae17df4.png">

**Comment by antictor** [comment]
I've made a start on the code just for my project. Will provide that to the team once it is settled and it can be adjusted to fit the designs

**Comment by m7kvqbe1** [comment]
For reference implementation started within standards here:

https://github.com/Royal-Navy/standards-toolkit/tree/feature/EN-723-modal-component

**Comment by antictor** [comment]
Dont alot of work on this within a project. I'll share what has been done. It takes into account needing solid dark areas, split areas, all sorts.

**Comment by hxltrhuxze** [comment]
Closing in favour of #207 as it contains a much more in depth proposal.
