### ISSUE TITLE
"About" page pattern

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#1970]
**Requirement**

Provide a pattern so that app teams can:

1. Display a 'Powered by' logo

2. Output technical info about their app, such as:
- Current version
- Debug information
This could be used for support calls etc.

**Acceptance Criteria:**

- [x] UX design: What does the link/logo look like and where does it sit
- [x] UX design: What does the target page / container look like
- [x] Write related docs content: How to use, when to use, what information to put there
- [x] Feedback from team
- [x] Development: build any required components

**Comment by k9dh3zij** [comment]
Agreed the following:

- We do not want to display a logo.

- The appropriate place for the functionality requested is the 'Support' option that exists in the [Masthead](https://storybook.royalnavy.io/?path=/story/masthead--default), shown below. It can be turned on/off by individual apps downstream.

![masthead](https://user-images.githubusercontent.com/73531035/108377774-46e45b00-71fc-11eb-8895-6c50d24f845a.png)

- Support should open in a [modal with no buttons](https://storybook.royalnavy.io/?path=/story/modal-examples--no-buttons). This keeps the user in-context, without breaking the user journey. 

![image](https://user-images.githubusercontent.com/73531035/108378579-09340200-71fd-11eb-95cd-f5283514fce6.png)

- The exact content (eg. support contact info, app version number etc) should be defined by individual apps downstream, depending on their needs. 

We will document this as a Pattern in the new Docs site.
