### ISSUE TITLE
Add deployment & app validation to npm smoketest

### ISSUE THREAD

**Issue by elglup** [Royal-Navy/design-system#1990]
Add an additional step to the npm smoketest workflow to serve up the test app and test access via a browser

- Run build and serve from localhost
- Access using Cypress / Puppeteer
- Run some rudimentary e2e tests

**Comment by elglup** [comment]
Still required to improve NPM smoketest

**Comment by m7kvqbe1** [comment]
Write a Cypress test checking that GlobalStyleProvider applies styles correct in the spawned CRA template app generated by the smoketest GitHub action.

See 'Developer notes' in this PR: https://github.com/Royal-Navy/design-system/pull/2376
