### ISSUE TITLE
Pagination - Allow users the ability to change number of pages shown

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#1995]
### Description
On Pagination component: 
https://storybook.royalnavy.io/?path=/story/pagination--default

There are a set amount of paging buttons/spacers rendered (7 in total). Because of this the pagination component does not fit well on small width containers. We would like the option to display for example only 5 of these buttons/spacers to make the component thinner.

**Comment by k9dh3zij** [comment]
Working on #2024 - Design: Pagination condensed version
 
It will address both this issue as well as #1996.

**Comment by k9dh3zij** [comment]
Design complete.
Please follow #2024 for updates, which is the dev ticket for this.
