### ISSUE TITLE
Pagination - Option to disable the 'Next' or 'Prev' text

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#1996]
### Description
On Pagination component: 
https://storybook.royalnavy.io/?path=/story/pagination--default

We would like the option to turn off the 'Next' and 'Prev' text on the corresponding buttons and leave it with just the arrow icons, this is to allow us to use pagination in smaller width containers.

**Comment by k9dh3zij** [comment]
Working on #2024 - Design: Pagination condensed version
 
It will address both this issue as well as #1995.

**Comment by k9dh3zij** [comment]
Design complete.
Please follow #2024 for updates, which is the dev ticket for this.
