### ISSUE TITLE
Timeline - Option to change the height of the rows

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#1997]
### Description
On Timeline component: 
https://storybook.royalnavy.io/?path=/story/timeline--with-custom-event-content

We pass the TimelineRow components a renderRowHeader function however we are unable to override the height of these rows. This leads to big white space gaps in our brick design of the timeline. The ability to override the height of these rows would allow us to make them smaller and the bricks that we have rendered appear closer together to minimise white space.

**Comment by thyhjwb6** [comment]
Does using styled-components help with this?

```javascript
const StyledTimelineRow = styled(TimelineRow)`
  height: 200px;
`
```

and then:

```javascript
  <Timeline
    hasSide
    startDate={new Date(2020, 3, 1)}
    today={new Date(2020, 3, 15)}
  >
    <TimelineTodayMarker />
    <TimelineMonths />
    <TimelineWeeks />
    <TimelineDays />
    <TimelineRows>
      <StyledTimelineRow name="Row 1" renderRowHeader={() => <span>row header</span>}>
        <TimelineEvents>
          <TimelineEvent
            startDate={new Date(2020, 2, 14)}
            endDate={new Date(2020, 3, 18)}
          >
            Event 1
          </TimelineEvent>
        </TimelineEvents>
      </StyledTimelineRow>
    </TimelineRows>
  </Timeline>
```

**Comment by thyhjwb6** [comment]
This change was covered in #1998.
