### ISSUE TITLE
Quick start guide is referencing a non-existent style sheet

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#201]
**Describe the bug**
the “Quick start” example (https://github.com/Royal-Navy/standards-toolkit) is referencing a non existent stylesheet:
import '@royalnavy/css-framework/dist/style.css'
should be
import '@royalnavy/css-framework/dist/styles.css'

**To Reproduce**
1. Try using the quick start guide.
2. See styles are not working.

**Expected behavior**
Load styles.css

**Desktop (please complete the following information):**
Browser.

**Comment by m7kvqbe1** [comment]
Fixed @ https://github.com/Royal-Navy/standards-toolkit/pull/215
