### ISSUE TITLE
page-data.json and icon-144x144.png are failing load

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#202]
**Describe the bug**
Some console errors. Files page-data.json and icon-144x144.png are failing load. Could be to do with a missing icon and Gatsby’s cache-control settings?
- Missing content in Components > Forms.
- BEM examples on ‘Container’ are incorrect:
<div class="rn-container--large">
should be
<div class="rn-container rn-container--large">
- Code example on ‘PhaseBanner’ is incorrect (closing tag).
<PhaseBanner>Custom html can go here. <strong>This part is in bold!</strong><PhaseBanner/>
should be:
<PhaseBanner>Custom html can go here. <strong>This part is in bold!</strong></PhaseBanner>

From FED feedback.

**Comment by m7kvqbe1** [comment]
re: page-data.json issue https://github.com/gatsbyjs/gatsby/issues/16097

**Comment by m7kvqbe1** [comment]
Resolved @ https://github.com/Royal-Navy/standards-toolkit/pull/233

Note that the page-data.json issue is a Gatsby problem (see previous comment). Awaiting from a fix upstream.
