### ISSUE TITLE
Fix 404 for /feedback page

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#204]
**Describe the bug**
Navigating to the `/feedback` page on docs.royalnavy.io results in a 404 page

**To Reproduce**
1. Scroll to the footer
2. Click on the Feedback button
3. See error

**Expected behavior**
Feedback page should either be created or the user should be redirected to the contact page

**Comment by m7kvqbe1** [comment]
Fixed @ https://github.com/Royal-Navy/standards-toolkit/pull/213
