### ISSUE TITLE
Allow Timeline Toolbar to be disabled

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#2044]
### Description
The timeline toolbar is not required by our project and it even can lead to unexpected behaviour.

Can we please make the Toolbar optional and allow the application using it to opt out.

**Comment by c9qsm62x** [comment]
Just like to add the current implementation is not compatible with application that use the range property. Application may want the timeline to be displayed in the 1/4 or year or 1/2 or year.
It seems that the range prop is unused.

https://github.com/Royal-Navy/design-system/blob/74d31a6ae8b73e3b46a905ec3e6639559cab58d5/packages/react-component-library/src/components/Timeline/Timeline.tsx#L114-L131
