### ISSUE TITLE
Spelling error on Nav docs site page

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#205]
**Describe the bug**
There are several spelling mistakes and grammatical errors in the Nav 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.royalnavy.io/components/nav
2. Scroll to the Nav properties table
3. Check last column of the navItems row

**Error**
An array of objects that must least contain a label. If no custom component is provided then provide a href, otherwise provide the the required property associated with the LinkComponent

**Corrected**
An array of objects that must **at** least contain a label. If no custom component is provided then provide a href, otherwise provide the ~the~ required property associated with the LinkComponent

**Comment by m7kvqbe1** [comment]
Fixed @ https://github.com/Royal-Navy/standards-toolkit/pull/211
