### ISSUE TITLE
TabSet - Allow className in the Tab component or surface is-active class

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#2050]
### Description
In the recent migration to styled components, the TabSet has lost the is-active class when the tab is active. We previously used this to override the styling on the active tab.

In order for us to be able to override the styling in the future we need either a className prop for Tab, in which we can utilise the onChange prop on TabSet to keep track of the active tab ourself and change the class respectively. Or we need the is-active class put on the active tab so we can override it.

**Comment by k9dh3zij** [comment]
Discussed with the team designer and decision was to revert visual design to the Design System default. 
There is no need to override the tab styling now, so closing this.
