### ISSUE TITLE
Using the toolkit without sass does not attach font styles to page

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#2057]
### Steps to reproduce
1 Create a new react application using create react app and the starter page and replace with a simple title and hello world
1 Add the royal navy toolkit packages to package.json
1 Add `import '@royalnavy/fonts'` to the index.tsx for the application
1 Start the app and inspect the page

The font family is not attached to the html element nor is the correct set of css rules applied to the h1 in the document.

<img width="975" alt="Screenshot 2021-03-03 at 10 37 17" src="https://user-images.githubusercontent.com/48056118/109793345-6f148680-7c0c-11eb-9dca-14918c2d0b89.png">

If the toolkit is moving to styled components and removing the need for sass to be included in a project then the correct fonts need to be loaded without having to include the toolkit sass file.

An example app can be seen at https://react-rest.therapywaffle.com/

The code for this is available at https://github.com/antictor/reacty

**Comment by m7kvqbe1** [comment]
We have looked into this and it looks like there are some other bits that also need moving out of the CSS framework (for example resets like normalize). This is due to be actioned soon.

**Comment by hxltrhuxze** [comment]
Closing in favour of #2344
