### ISSUE TITLE
Icon library

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#206]
## Description

We need an icon library for Standards. This should include Royal Navy (and potentially coalition / NATO) air and sea assets.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

_Used in 3x exemplars._

## Details / user needs

Icons are easily recognisable. If you use common icons in your designs, your audience will recognise them instantly, helping with navigation and tasks.

We need a comprehensive library of icons in a consistent style. These should be scale-able in size and with the ability to re-colour as required by the Application design.

We should include in this accurate deceptions of Royal Navy and coalition partner Units (air and sea). 
In our user testing, participants were very distracted if these weren't accurate, so care should be taken in making these accurate. In the case of ships, this should be down to the individual vessel, not just the class.

_Used in 3x exemplar projects_

## Variations

Ability to present icons in different states such as 'active', 'inactive', 'hover' etc.

## Questions
- How will we license icons for distribution? Will we expect 3rd parties to buy their own licenses or will NELSON provide a license?
- Will we create icons in-house or use an external provider?
- How do we prioritise what icons we need?
- Do we need to specify usage for each icon, so that they are consistently used?

## Definition of done
- [x] Icon library approach is decided on
- [x] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [x] All questions laid out in this ticket have been resolved 
- [x] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by m7kvqbe1** [comment]
https://github.com/Royal-Navy/standards-toolkit/pull/273
