### ISSUE TITLE
Checkbox misalignment

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#2064]
The checks inside checkboxes are misaligned in some browsers. The white check does not align vertically in the middle of the blue box. Although this is a small issue it doesn't look right.

This is the screenshot taken in Firefox / Ubuntu:
![image](https://user-images.githubusercontent.com/52033457/109981873-3b635a80-7cf9-11eb-93c3-4eb49fb203ce.png)

**Comment by m7kvqbe1** [comment]
This also appears to be a problem for breadcrumbs.

**Comment by thyhjwb6** [comment]
<img width="413" alt="Screenshot 2021-04-13 at 11 55 09" src="https://user-images.githubusercontent.com/56078793/114541815-1a265000-9c4f-11eb-814a-7cf59815df52.png">

@m7kvqbe1 having tested the `Breadcrumbs` with FF it is not immediately obvious there is an issue. Let's create a separate ticket with the issue if one still exists.
