### ISSUE TITLE
Number clicker component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#208]
## Description

A numerical input component that allows users to increment values by a set amount.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Users often need to be guided as to:
- The fact that an input is numeric
- It can only be incremented as a specific value (e.g. multiple of 10)
- It has a specific unit, for example percentage, hours or £££

We need a component that allows this input to be made in a quick, accessible and easy to comprehend way.

We should ensure that when using a mobile keypad, the numeric keypad is selected when the element is in focus.

![number-clicker](https://user-images.githubusercontent.com/52033457/63095431-1feffd80-bf63-11e9-979f-de5265b0fadf.png)

_Used in 3x exemplar projects_

## Variations

- Pre and post fixed fixed functionality
- Enabled, disabled, in focus, hover states

## Questions

- There has been some discussion about how to treat error scenarios when the user inputs a value that is not a valid increment. This needs further discussion with the Product Owner.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Number Clicker
The simple number clicker can either have a value entered in the same manner as a text input, or the user can use the incremental up/down arrows.

<img width="468" alt="Screenshot 2019-08-27 at 17 05 33" src="https://user-images.githubusercontent.com/48090803/63788183-e9b06780-c8ec-11e9-9b81-c555be2f1b2a.png">


### Abstract link
https://share.goabstract.com/e13d7d86-745f-4c19-bc04-d57542754099?sha=c7226d3e551d7d83470dbb287d92cbc868ae406d
