### ISSUE TITLE
DatePicker: The end and start date highlight text colour is incorrect

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#2084]
The end and start date highlight text should be white. It appears that this is a recent regression.

<img width="514" alt="Screenshot 2021-03-09 at 12 47 11" src="https://user-images.githubusercontent.com/48086589/110472691-928c7500-80d5-11eb-8327-e052890e2831.png">

**Comment by thyhjwb6** [comment]
This has been fixed as part of #2083.
