### ISSUE TITLE
Select: The positioning of a selected value appears to be incorrect

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#2086]
The positioning of a selected value appears to be incorrect. This appears to be a recent regression.

<img width="526" alt="Screenshot 2021-03-09 at 12 52 19" src="https://user-images.githubusercontent.com/48086589/110473408-63c2ce80-80d6-11eb-9fa0-12abdb7bd4c2.png">

**Comment by c9qsm62x** [comment]
I've also experience the same issue on version 2.30.4. 
When expecting the HTML document I saw that react-select css (emotion) was being injected after the design system style component.

**Comment by jpveooys** [comment]
Sometimes the placeholder text also isn't vertically centred (but a bit too low). However, both problems seem to either occur together or both not occur (for example, they might both show in Storybook, but if I refresh the page then it is usually OK).

![select-refresh](https://user-images.githubusercontent.com/66470099/111188502-04b8fa00-85ad-11eb-9859-aa84d857226d.gif)

**Comment by thyhjwb6** [comment]
This issue is being addressed as part of #2091.
