### ISSUE TITLE
NumberInput: Unit is selectable and makes it difficult to edit value

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#2087]
When the NumberInput is used with a unit and label the unit is selectable as text. 

This makes it difficult to interact with and focus the input with a mouse. Same applies for the label.

![2021-03-09 12 55 58](https://user-images.githubusercontent.com/48086589/110473994-1004b500-80d7-11eb-8cac-371adfff1712.gif)

**Comment by k9dh3zij** [comment]
This is definitely an issue. For v3 of Forms, we've specified that units must not be part of the input box. They must be shown using a prefix/suffix instead.

For the current version I believe the simplest solution would be to make the entire Numberinput component clickable but set the focus to the input if a user clicks on the unit or label.
