### ISSUE TITLE
NumberInput: Add keyboard control for stepping value (up and down arrows)

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#2088]
Add keyboard control to allow an end-user to step the NumberInput using the up and down arrows.

**Comment by k9dh3zij** [comment]
Below is the current spec for Forms v3. We may want to add some kind of support for this now:

**Setting a value**

Users can set a value by:

1. **Typing the value** directly into the Number input field.

1. **Using the interface plus/minus buttons**.
  - Pressing the **plus** button will **increase** the current value by an amount equal to the preset step.
    - If there is no current value, the input should automatically start either at 0 or the valid value nearest to 0.
  - Pressing the **minus** button will **decrease** the current value by an amount equal to the preset step.
    - If there is no current value, the input should automatically start either at 0 or the valid value nearest to 0.

1. **Using the keyboard**
  - Pressing the **↑ or → or +** key will **increase** the current value by an amount equal to the preset step.
    - If there is no current value, the input should automatically start either at 0 or the valid value nearest to 0.
  - Pressing the **↓ or ← or -** key will **decrease** the current value by an amount equal to the preset step.
    - If there is no current value, the input should automatically start either at 0 or the valid value nearest to 0.

**Comment by k9dh3zij** [comment]
This has been specced for v3 as per comment above. We will therefore not introduce it in v2.
