### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#209]
## Description

Standard select input (as per browser native functionality).

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Select elements are core HTML components. Users need them in forms and as standalone elements.

## Variations

- Pre and post fixed fixed functionality
- Enabled, disabled, in focus, hover states

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
Closing this in favour of #192 as we already have designs/discussion inside that issue.
