### ISSUE TITLE
Update Storybook to use docs addon and dynamically generate prop tables and live examples

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#2094]
https://www.npmjs.com/package/@storybook/addon-docs

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md

- Auto-generate interface documentation and live examples with 'controls'.

- Ensure that Storybook is also supplemented with README text for components where necessary.

- Also ensure that exposed composable sub-components have their interfaces documented dynamically.

**Comment by thyhjwb6** [comment]
Something to consider is that there is an error on the `Pagination` which is not visible in Storybook. Global spacing needs to be considered.

This is also the case with `RangeSlider`.
