### ISSUE TITLE
Rules component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#210]
## Description

A vertical or horizontal line. Used for dividing up areas of content.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Rules play an important part in layout out the content of the page, making it easier for users to read, understand and interact with screen content.

We need specific guidance for usage, including on colour. Rules can be placed on a number of background objects and colours, which should be factored into the design.

_Used in 2x exemplar projects_

## Variations

- Solid rule
- Dashed rule
- Dotted rule
- Different coloured versions

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
Closing as PR has been raised #263
