### ISSUE TITLE
Switch component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#212]
## Description

A switch component is a joined series of two or more buttons, representing a choice to the user. One or more buttons can be selected at a time.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Users need a simple way to switch between a variety of named options. One or more option can be active / selected at a time. It should be clear which options are currently selected.

_Used in 2x exemplar projects_

## Variations

- Versions where initially one of the switch options has been pre-selected
- Allow the user to deselect both options
- Enabled, disabled, in focus, hover states

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
Closing in favour of #194 as this is a duplicate ticket.
