### ISSUE TITLE
Timeline - Range prop introduces strange behaviour on different zoom levels

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#2120]
When using the Timeline with a range prop (example range={3}), the behaviour that is expected is that the amount of months shown on default zoom level is 3. Then on a zoom in and out, the amount of x (years, weeks etc) should be 3 times the normal amount.

Instead what happens is the width of the individual columns are 3 times as wide not the amount of x (years, weeks etc).

This has been shown to one of the DS devs.

**Comment by thyhjwb6** [comment]
This will ultimately need a proper look from the design perspective before more dev work.

I will speak with @s24y85u2 to see how we can help in the meantime.

**Comment by thyhjwb6** [comment]
Having spoken with @s24y85u2 I have opened a spike #2191

**Comment by thyhjwb6** [comment]
Based on development of spike #2191 and feedback received this can now be moved forward.

Spike branch: https://github.com/Royal-Navy/design-system/commit/e502962e62c09270b5a892117518ab93f52b7173

- use `isFullWidth` prop for backwards compatibility
- width will expand to full width of viewport or parent
- width will never be less than `unitWidth * numberOfDays`
- the spike was not perfect with zooming and formatting so special attention is needed in this area
