### ISSUE TITLE
ContextMenu - Option to open on the left

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#2122]
### Description
The ContextMenu currently only opens up on the right side of the point in which you click. We would like it to optionally open on the left hand side. This is because when you click something that is next to the end of the screen on the right, the menu opens off the screen.

**Comment by m7kvqbe1** [comment]
This ticket is related to https://github.com/Royal-Navy/design-system/issues/2131

We will probably look to replace the positioning engine for this component with a third party library that intelligently calculates whether to display the component above, below, left or right of the target relative to the viewport.
