### ISSUE TITLE
Right-click context menu scroll bug

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#2131]
### Steps to reproduce
1. Right click on a specific interface element that should open right-click contextual elements
2. Context menu appears
3. Scroll with mouse wheel
4. Context menu remains in position relative to the page, not the interface element. This creates a strange situation where the menu appears completely out of place on the page.

I guess you could close the context menu on  scroll e.g. as Chrome works, or keep it aligned to the trigger UI element.

This is affecting our exemplar project and is a fairly substantial bug for us.

https://user-images.githubusercontent.com/52033457/111975185-36bfe400-8af8-11eb-9f44-c50f59c399ba.mp4

**Comment by m7kvqbe1** [comment]
We feel that it may be best to lock the viewport scroll when the context menu is in an open state as this matches the behaviour of a native context menu.
