### ISSUE TITLE
Hyperlink component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#214]
## Description

A linked piece of text that navigates users to another page or area of an Application.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Hyperlinks are a well established and known UI component that uses are familiar with.

It should be clear what text is marked up as a hyperlink. There should be appropriate states for active, focus, hover, visited etc.

Clear guidance should be provided on hyperlink usage.

See also https://rn-nelson.atlassian.net/browse/EN-567.

_Used by 2 exemplar projects_

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by 09txzS1qs** [comment]
There are no screenshots in the ticket, assume that hyperlinks will look like the attached screenshot from the docsite. @hxltrhuxze can you add images for the various states please before sign off? 
![image](https://user-images.githubusercontent.com/48475355/64023234-c1647b00-cb2f-11e9-88ad-bca80181204b.png)

**Comment by hxltrhuxze** [comment]
Closing as PR has been raised #263
