### ISSUE TITLE
Avatar component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#216]
## Description

Representation of the user within the Application. This could be a simple graphic (such as the users initials), or an uploaded picture.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Users have come to expect an area in an Application where there settings and preferences are accessed from. Since this is personalised to them, a graphical representation of the user helps make the connection to these settings.

This was discussed recently and the initial suggestion is that it takes the initials of the user.

_Used by 2x exemplar projects_

## Questions

- The context of the avatar should be considered in the design. It may form part of a larger user profile area.

## Definition of done
- [x] The Sketch file is updated with the component
- [x] There are screenshots of all component variations in this ticket
- [x] All states are included if applicable (default, hover, active, focus)
- [x] A design documentation PR is linked from this ticket
- [x] All questions laid out in this ticket have been resolved 
- [x] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Avatar
The Avatar component is a very simple component containing the first and last name initials of a particular user. It comes in two varieties: Light and Dark.

<img width="233" alt="Screenshot 2019-08-22 at 15 11 57" src="https://user-images.githubusercontent.com/48090803/63521888-35c76a80-c4ef-11e9-93aa-9c0ac71ecb19.png">

When hovered on, the background transitions to the active blue state we have used throughout our components.

The general use for the Avatar component is to provide a quick link to a user's profile/settings etc. Once the user clicks the Avatar, the profile page should display - this however is not included in the Avatar component as it is its own separate pattern.

### Abstract Link
https://share.goabstract.com/980a50f0-ce73-473b-98aa-2a8367e4d488?sha=a19abdf1782976aa23eba663723e11d715275cf0

**Comment by antictor** [comment]
Update the existing non-documented component to match designs and add documentation

**Comment by antictor** [comment]
PR ready #265

**Comment by ghost** [comment]
Noting our retro discussion about adhering to our definition of done, could @antictor take a look at the DoD in the ticket description and check everything's complete now this is `done` please?
