### ISSUE TITLE
No highlight for focussed icons (applies to several components)

### ISSUE THREAD

**Issue by k9dh3zij** [Royal-Navy/design-system#2178]
This seems to apply to at least Select and DatePicker:

- Click in the field 
- Press Tab once

Focus is now on the 'collapse' icon, however there's no visual cue to that effect.

Expectation:
At a minimum, I'd expect the default browser dotted border to indicate where the focus is.

https://user-images.githubusercontent.com/73531035/113886810-dfd53280-97b8-11eb-92cc-fefa71152a16.mov

**Comment by thyhjwb6** [comment]
This needs design input and should be applied to all instances.

**Comment by hxltrhuxze** [comment]
This will be solved by Forms v3
