### ISSUE TITLE
Button group component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#219]
## Description

A number of buttons that are physically joined together.

## Details / user needs

A series of grouped buttons, indicating to the user they perform related or similar actions. For example: zoom in | zoom out. The buttons should be physically connected.

It should be possible to label the button group.

This should follow the standard button conventions closely.

**Note that this is different to a switch were one or more buttons can be active.**

_Used in 2 exemplar projects_

## Variations

- Enabled, disabled, in focus, hover states 

## Questions

Outstanding questions for the Product Owner, Designers or Developers.

## Definition of done
- [x] The Sketch file is updated with the component
- [x] There are screenshots of all component variations in this ticket
- [x] All states are included if applicable (default, hover, active, focus)
- [x] A design documentation PR is linked from this ticket
- [x] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Button Groups
Button groups connect secondary buttons together into a single, unseparated block. They can consist of a group of icons or labels, however these should not be mixed.

### States

<img width="349" alt="Screenshot 2019-09-20 at 12 48 12" src="https://user-images.githubusercontent.com/48090803/65324714-ed11d880-dba4-11e9-9d3b-bb5efab893cb.png">

The Button Group has 3 states: Default, Hover/Focused, and Disabled. There is no Active state for Button Groups as they function the same as regular buttons - you click for an action and it reverts to its default state. If it's required to maintain state for the selected option, the Switch component should be used instead.


### Abstract Link
https://share.goabstract.com/f14a16f5-12fa-43cb-86fb-405a21cb432b?sha=9cb86ee7d25366567fde55baef1330d320279a9a

**Comment by ghost** [comment]
Is there a maximum number of buttons we would have in a button group? It feels like it would be helpful to others (specifically teams using this w/o a designer on the team) to guide them on that? Enforcing feels a bit strong but perhaps it’s appropriate if we feel strongly about it. Sounds like general agreement on 5 and that we'll capture that in the docs.

Would you ever use icons in this sort of button group?

**Comment by ghost** [comment]
I think this is 'signed off' from my perspective provided thought has gone into the comments above (which it sounds like there has). It'd be good to document some answers/thoughts @hxltrhuxze

**Comment by hxltrhuxze** [comment]
@xdobtqletrmn 

> Is there a maximum number of buttons we would have in a button group?

I think we should keep this the same as how we tackle the Switch component, which has a maximum of 5.

> Would you ever use icons in this sort of button group?

Absolutely. Button groups are simply wrappers around the existing button component. It provides a nice way to group a set of actions, and it also visually removes the borders/radius/gaps between each button. The Button components inside the Group will function exactly the same as they do now, with all the features we have added (including icon support.)

**Comment by antictor** [comment]
Development done. Just need to add design documentation
