### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#222]
## Description

Similar in appearance to a select component, a dropdown can contain a variety of different forms of content such as navigation items, filters etc. It is accessed via a button.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Dropdowns are a familiar interaction element. They are used to wrap extended functionality into an interface under the wrapper of a single description.

Dropdown's should be designed with flexibility in mind. They can contain a number of types of information and can require different actions from users.

Some design considerations:
- Dimensions of dropdown - ideally this should be left to the App designer
- Content of the dropdown should be divided into relevant sections
- How will the dropdown be labelled?
- How will the content of the dropdown be accessible?
- The title of a dropdown can contain more than just text: an icon or label might be present

_Used in 2x exemplar projects_

## Definition of done
- [x] The Sketch file is updated with the component
- [x] There are screenshots of all component variations in this ticket
- [x] All states are included if applicable (default, hover, active, focus)
- [x] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [x] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Dropdown Component

<img width="797" alt="Screenshot 2019-09-12 at 11 46 43" src="https://user-images.githubusercontent.com/48090803/64778140-65e4b500-d553-11e9-9a18-ddcb5c5bcc83.png">

The Dropdown component provides a way to group/hide multiple actions under one clear heading. It looks similar to the select component, but with a few differences:

- The Dropdown label is fixed. When using a select, the item clicked on in the list will sit beneath the label in the main select input area. The Dropdown doesn't do this, as all the items in the dropdown are independent actions that are not being "set" by the component.
- The main Dropdown bar can accept an icon on the left of the Dropdown Label.
- The Dropdown sheet that appears on click is visually separated from the main Dropdown bar. This is to help distinguish it from the Select component.


### Dropdown item
The Dropdown item has multiple different variations:
<img width="692" alt="Screenshot 2019-09-12 at 12 11 16" src="https://user-images.githubusercontent.com/48090803/64779702-8f531000-d556-11e9-82ec-fd0c627db26b.png">

1. Default Items
Default items don't have an icon on the left hand side. They have 3 variations: Visible, Hidden, and Right aligned text. Right Aligned text is used to convey things like keyboard shortcuts.


2. Icon Items
Icon items have a left aligned icon. They also come in the variations: Visible, Hidden, and Right aligned text.

The only icon that can appear on the right is a visible/invisible indicator - this is to ensure consistency. We don't want multiple Dropdowns having a mismatch of icons, where some are left aligned and some are right aligned.

### Design Considerations
**Dimensions of dropdown - ideally this should be left to the App designer**
Unsure what's meant by this - @aavvjg6j could you clarify this point?

**Content of the dropdown should be divided into relevant sections**
**How will the dropdown be labelled?**
The Label is fixed within the main Dropdown bar.

**How will the content of the dropdown be accessible?**
We've added keyboard support to the Select component, so presumably it won't be too difficult to replicate here.

**The title of a dropdown can contain more than just text: an icon or label might be present**
There is a place to add an icon to the left of the Label. In this component, the Label is the Title as it does not change based on user input.

**Comment by ghost** [comment]
Looks and feels fine to me. Some noob observations:

1. It'd be good to tease out that point from @aavvjg6j about drop down dimensions. Here's my interpretation of the point as a question: "As an application designer/builder, will I be able to set the width of the drop down component?
_or will that be determined by the lengths of the strings in my dropdown sheet or constrained by the design system?_

2. When we come to write the docs, it might be worth illustrating your 3 bullets which tell the reader what the differences are to the select component - in addition to describing them in text as you've done. Picture = 1000 words and all that.

3. I noticed at the very top of this thread you said it could be used for filters - you might want to select multiple things when filtering, right? Will it support that or is it the wrong component for that sort of selecting?

4. Is it worth providing a visual example of a drop down being divided into multiple sections (one of the design considerations), presumably with a horizontal rule or similar? Again, perhaps a consideration for the doc site.

5. What would I expect to see happen when i click on one of the options?

**Comment by hxltrhuxze** [comment]
In answer to the questions:

1. The width of the dropdown sheet will be calculated based on the length of your strings - there is no need for a designer/developer to manually adjust this.

2. Noted, will do.

3. There are two ways of approaching filters. With the Dropdown design, clicking on an item can toggle the visibility of something on or off (hence the eye icon on the right hand side). It does not work like the filtering on GitHub issues etc, where multiple tags can be added to the filter. That should be a feature of the Select.

4. Yeah totally.

5. Exactly the same thing that would happen if you clicked on a regular button - the Dropdown is just a concise way to group these actions. It doesn't do anything special in its own right.

**Comment by antictor** [comment]
Just one comment for now. The design is very different to the previous versions seen so the estimates were based around that. This may take a little longer.
