### ISSUE TITLE
Notification component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#223]
## Description

The notification component displays important messages that are relevant to the user. These messages may be triggered while the user is in the App, or whilst they are away.

## Component classification

Is this component an atom, molecule or organism?
- [ ] Atom
- [ ] Molecule
- [x] Organism

## Details / user needs

We need some way of highlighting to users that there are important messages they should attend to, but without being highly intrusive in the interface,

Some design considerations:
- The trigger element should indicate whether there is a notification present, and the number of notifications
- The component should include a trigger element, such as an icon or button
- The layout of notifications themselves should be flexible. Each Application is likely to have very different needs
- Each notification should contain a brief description, and a call-to-action, or ability to dismiss
- Notifications need to be positioned prominently on the page so users don't miss them

_Used in 2x exemplar projects_

## Questions

- How will the user access long list of notifications (10+)?
- How will the user access an archive of notifications - do we need an archive? This mighr be application specific.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Notification Sheet

<img width="726" alt="Screenshot 2019-08-27 at 17 26 18" src="https://user-images.githubusercontent.com/48090803/63789704-cc30cd00-c8ef-11e9-8cf0-c3a8eec37dac.png">

## Answers to questions
- How will the user access long list of notifications (10+)?
The notification sheet is _not_ the notification page. That is a separate page that contains all the notifications, included expanded descriptions.
- How will the user access an archive of notifications
See above.

### Abstract Link
https://share.goabstract.com/e13d7d86-745f-4c19-bc04-d57542754099?sha=c7226d3e551d7d83470dbb287d92cbc868ae406d

**Comment by 09txzS1qs** [comment]
@hxltrhuxze the scope of this component is unclear from the screenshots and description - happy with the simple bell icon, but to what extent with the notification sheet be standardised?

**Comment by hxltrhuxze** [comment]
@09txzS1qs In my mind, the notification sheet should be standardised into having:
- Icon (either avatar, or appropriate action icon)
- Title
- Date
- Description (optional)

This component is intended to work much like the Facebook notification sheet - it provides a brief overview of an event has happened.

Maybe @antictor can weigh in on this - I know we briefly discussed the notification sheet yesterday.

**Comment by antictor** [comment]
The avatar should be made optional and some stuff should be optional too and the rest like title and description mandatory so this will be doable that way

**Comment by ghost** [comment]
In addition to the 4 things listed in [this comment](https://github.com/Royal-Navy/standards-toolkit/issues/223#issuecomment-526150101), would we not expect for there to be at least one action on the notification (`dismiss`)? This line in the original ticket made me think of it...
> Each notification should contain a brief description, and a call-to-action, or ability to dismiss

Otherwise this looks good.
