### ISSUE TITLE
Textarea component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#224]
## Description

A large box for the user to enter multi line textual content.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

Interfaces often require users to enter larger passages of text. The textarea is a common element that facilitates this. Generally textareas are understood well by users.

## Variations

- Version with a character limit / countdown

## Questions

- Do we want to allow users to resize textareas?
- Is textarea a suitable name? This is more of a developer term. "Multi-line text input" is more in keeping with the "single line text input

## Definition of done
- [x] The Sketch file is updated with the component
- [x] There are screenshots of all component variations in this ticket
- [x] All states are included if applicable (default, hover, active, focus)
- [x] A design documentation PR is linked from this ticket
- [x] All questions laid out in this ticket have been resolved 
- [x] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Textarea Component
The textarea component is very similar to the Text Input component https://docs.royalnavy.io/components/forms/input

It has 3 states: Default, Active and Filled:
<img width="633" alt="Screenshot 2019-08-22 at 13 44 11" src="https://user-images.githubusercontent.com/48090803/63516500-e419e280-c4e4-11e9-9615-d357c3285ff9.png">

## Abstract link
https://share.goabstract.com/e13d7d86-745f-4c19-bc04-d57542754099?sha=f70b6f23608280e0e8071701747cb626db426718

## Questions
- Do we want to allow users to resize textareas?
I believe we should have an option to allow vertical resize *only*. Horizontal resizing causes the document to reflow and can break layout, so we should avoid it.
- Is textarea a suitable name? This is more of a developer term. "Multi-line text input" is more in keeping with the "single line text input
Yes, textarea is the most appropriate name for this component. It is a standard `HTML` tag and is the commonly used name for this component.

**Comment by hxltrhuxze** [comment]
PR ticket: #264

**Comment by antictor** [comment]
I have taken some of the work done already for the component from one branch, other work done by design and have continued with it to get it to the point it is ready for review in a new branch.
