### ISSUE TITLE
Date and time picker component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#225]
## Description

A way for a user to select a date and time. Note that there is a separate (but related) component for date and time RANGE selection.

## Component classification

Is this component an atom, molecule or organism?
- [ ] Atom
- [x] Molecule
- [ ] Organism

## Details / user needs

Users often need to select dates and times to complete simple tasks.

Some design considerations:
- Should allow users to key in a date / time
- Should allow users to graphically select a time and date
- Should include optional timezone selection. This is especially relevant as users are likely to be globally distributed
- Should allow users to increment times by using arrow keys or similar
- Should allow for set time periods to be selected, for example in six-hourly increments

_Used in 2x exemplar projects_

## Variations

- Version that just allows a date to be selected
- Version that just allows a time to be selected 

## Questions

- What time fidelity is useful here? Minutes, seconds?

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
Variation of this component can be found in the closed issue #226

**Comment by hxltrhuxze** [comment]
# Date & Time Picker

### Inputs
The Date and Time inputs look similar to the regular text input, however they have additional formatting to add the `/` to the dates and `:` to the time. Clicking either the Date or Time input will open a dropdown containing the pickers.
<img width="434" alt="Screenshot 2019-11-18 at 12 20 09" src="https://user-images.githubusercontent.com/48090803/69052028-dc8faa00-09fd-11ea-933d-a85c3a65ac9e.png">
### Date Picker
The Date picker has two variations - A Single Date Picker and a Single Date with Quarterly Hour picker.
<img width="714" alt="Screenshot 2019-11-18 at 12 20 17" src="https://user-images.githubusercontent.com/48090803/69052029-dc8faa00-09fd-11ea-8a05-decdd666ec47.png">
### Start and End
Often, we'll need the user to pick a start and end date. This has two calendars side-by-side, with arrows to navigate left/right between months. Click on either calendar to add a start date. Clicking again will add the end date and highlight all days in the range. This picker also has the variation to allow the user to select and Quarterly hour period.
<img width="679" alt="Screenshot 2019-11-18 at 12 20 24" src="https://user-images.githubusercontent.com/48090803/69052030-dc8faa00-09fd-11ea-923a-1978bf88c047.png">
### Time Picker
Finally, the Time picker is a simple dropdown with three scrolling columns - each for hour/minute/second.
<img width="211" alt="Screenshot 2019-11-18 at 12 20 34" src="https://user-images.githubusercontent.com/48090803/69052033-dd284080-09fd-11ea-81a9-6cd7ff928d57.png">
### Timezones
This will be something we'll need to figure out moving forward and may not be appropriate for v1 of this component. We will need to decide how we handle time zones for users, and if it's something we can automatically calculate based on the user's location or the task start/end location.

**Comment by m7kvqbe1** [comment]
First iteration of this is now just awaiting design documentation.
