### ISSUE TITLE
Data and time RANGE picker component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#226]
## Description

A way for a user to select a date and time RANGE. Note that there is a separate (but related) component for date and time ONLY selection.

These two issues share a number of items in common.

## Component classification

Is this component an atom, molecule or organism?
- [ ] Atom
- [x] Molecule
- [ ] Organism

## Details / user needs

Users often need to select dates and times to complete simple tasks.

Some design considerations:

- Optionally should allow users to select pre made date/time ranges, for example 'the last 30 days'.
- Should allow users to key in a date / time range
- Should allow users to graphically select a time and date range. This could be done with a single or multiple calendar view
- Should include optional timezone selection. This is especially relevant as users are likely to be globally distributed
- Should allow users to increment times by using arrow keys or similar
- Should allow for set time periods to be selected, for example in six-hourly increments

_Used in 2x exemplar projects_

## Variations

- Version that just allows a date range to be selected
- Version that just allows a time range to be selected

## Questions

- What time fidelity is useful here? Minutes, seconds?

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
Closing this issue in favour of #225 as this is a variation of that component.
