### ISSUE TITLE
Dialog sizing bug

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#2269]
When users have a low screen resolution, or if dialogues contain a lot of content a dialogue's size can often exceed that of the available space. In this case the content is not visible, and things like the action buttons are off screen.

Ideally there would be a mechanism to mitigate this. An obvious candidate is an internal scroll bar on the dialogue.

There could also be a rule to prevent dialogues exceeding the size of the available screen space.

I have some images of this - I can't share them here but when this ticket is allocated please get in touch.

Thanks.

**Comment by thyhjwb6** [comment]
After discussion:

> my personal preference would be for Dialog to have an internal scrollbar if [content] (taller than) [dialog viewport]

> best to set the dialog to a max height of 100vh or something and then have the content box in the middle overflow-y: scroll
