### ISSUE TITLE
Popover component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#227]
## Description

A popover is a self-contained modal or dialogue that appears in context next to a trigger element. It contains more content that a tooltip, but is directly related to a trigger element in the same way as a tooltip.

## Component classification

This component is a Molecule.

## Details / user needs

Popovers provide larger volumes of contextual information to a specific element on an interface. This content can be informative, or include interactive elements.
- Shows on hover.
- Can display left, right, above or below the target element.
- Can take any JSX.
- Popover by default only supplies the wrapper.
- If just putting content, use content sub-component.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by ghost** [comment]
@aavvjg6j - we thought you might have some other examples of where the popover is being designed in another application. Can you add anything to the Details/User needs section above please?

**Comment by antictor** [comment]
FB will need this early on, and there is a basic version already in place. Would be good to get some good examples of it's requirements documented and finish it up.

**Comment by hxltrhuxze** [comment]
The Popover functions similarly to the tooltip component, but with space for rich content. This design contains just the Frame.

<img width="418" alt="Screenshot 2019-11-04 at 16 19 49" src="https://user-images.githubusercontent.com/48090803/68137526-0d141600-ff1f-11e9-83d1-2b452c197150.png">

A working example of what could _potentially_ be created with the Popover.
<img width="418" alt="Screenshot 2019-11-04 at 16 20 35" src="https://user-images.githubusercontent.com/48090803/68137630-346ae300-ff1f-11e9-9792-684e3adab3a4.png">
