### ISSUE TITLE
Code snippet in Button Component Variants is incorrect

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#229]
**Describe the bug**
The Button Variant examples in the Develop tab on the docs site has missing `=` for some of the rules.

**To Reproduce**
1. Go to https://docs.royalnavy.io/components/button
2. Click on the Develop tab
3. Scroll down to the Variants block
4. Check the code block.

**Expected behavior**
The code examples should be consistent and all have `onClick={action}` rather than the `onClick{action}` currently been shown by some of the examples.

**Screenshots**
<img width="941" alt="Screenshot 2019-08-19 at 10 29 05" src="https://user-images.githubusercontent.com/48090803/63254832-5764ef80-c26c-11e9-8f36-a1f3da4f0cd0.png">

**Comment by m7kvqbe1** [comment]
Resolved @ https://github.com/Royal-Navy/standards-toolkit/pull/233
