### ISSUE TITLE
Phase Banner documentation has broken formatting

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#230]
**Describe the bug**
On the Phase Banner documentation page, the docs underneath the Anatomy section in the design tab has its markdown formatting broken.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.royalnavy.io/components/phase-banner
2. Scroll down to the Anatomy section in the Design tab
3. All list items are on the same line

**Screenshots**
<img width="1094" alt="Screenshot 2019-08-19 at 13 30 51" src="https://user-images.githubusercontent.com/48090803/63265835-68baf580-c286-11e9-8f3f-2b2aa72f10ba.png">

**Fix**
To fix this issue, a return is needed to be placed between the SVG image and the next block of markdown content to ensure correct rendering. This is currently a limitation of MDX files.

**Comment by m7kvqbe1** [comment]
Resolved @ https://github.com/Royal-Navy/standards-toolkit/pull/233
