### ISSUE TITLE
DatePicker shows incorrect red border after clicking in text input

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#2300]
### Steps to reproduce

1. Go to https://storybook.royalnavy.io/?path=/docs/date-picker--default
2. Click in the date picker text input area (not on the down arrow)
3. Click on a date from the calendar-based picker below

A red border incorrectly appears around the control.

### Demo

![date-picker-invalid](https://user-images.githubusercontent.com/66470099/116536004-5955d180-a8dc-11eb-8176-1289ca9e590c.gif)

**Comment by thyhjwb6** [comment]
This appears to be fixed with recent updates. Will wait for the deployment of Storybook tonight before closing this.

**Comment by jpveooys** [comment]
Note the following when testing:

> Click in the date picker text input area **(not on the down arrow)**

**Comment by s24y85u2** [comment]
This has not been fixed and still occus on date ranges.

https://storybook.royalnavy.io/?path=/docs/date-picker--range

Click inside the input, not using the dropdown. Select two different dates, then click outside the picker. Then click inside the input again and outside again. Notice the error.
