### ISSUE TITLE
`styled-components` Context Provider (CSS Framework deprecation)

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#2344]
As we are moving the Design System to Styled Components, we should look to deprecate the **CSS Framework** package. In order to do so, we should create a `<ContextProvider>` component that wraps applications using the RNDS. This provider would contain everything in the CSS framework that isn't currently covered by Styled Components.

## Acceptance criteria
- [x] Investigated usage of utility classes in downstream applications 
- [x] `<ContextProvider>` component created, containing:
  - [x] `@font-face` rules to load `Lato`
  - [x] Resets
  - [x] Base styles (Normalize)
- [x] CSS Framework marked as Deprecated

**Comment by thyhjwb6** [comment]
My suggestion is that we break this into three separate parts so we could investigate and deprecate first and then implement the main change after.

**Comment by m7kvqbe1** [comment]
We have broken the context / theming part of this out into a separate ticket: https://github.com/Royal-Navy/design-system/issues/2351
