### ISSUE TITLE
Broken link fix on styles overview page

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#236]
**Describe the bug**

The link to 'colour' on the styles page is broken.
https://docs.royalnavy.io/styles

It links to https://docs.royalnavy.io/styles/colour and

**To Reproduce**
1. Go to https://docs.royalnavy.io/styles
2. Click on 'colour'
3. See 404 (https://docs.royalnavy.io/styles/colour)

**Expected behavior**
1. Go to https://docs.royalnavy.io/styles
2. Click on 'colour'
3. Directed to https://docs.royalnavy.io/styles/colours. Note the S on 'colours'

**Comment by hxltrhuxze** [comment]
Closing as fixed by #238
