### ISSUE TITLE
Checkbox.js `isChecked` prop has been deprecated, use `checked` and `defaultChecked`

### ISSUE THREAD

**Issue by cpoDesign** [Royal-Navy/design-system#2371]
### Steps to reproduce
1. *Step 1*
Use the following code
`
import {  Checkbox } from '@royalnavy/react-component-library'
`
2. *Step 2*
`
        <div className="checkbox">
          <Checkbox
            name="nodataCheckBox"
            label="No data"
            defaultChecked={row.noData}
            isChecked={isNumericDisabled}
            onChange={onNoDataCheckBoxChanged}
          />
        </div>
`

**fileName:**
Checkbox.js

**FilePath**
http://website:8080/static/js/RootPath:/node_modules/@royalnavy/react-component-library/dist/es/components/Checkbox/Checkbox.js

### Minimal reproduction

1. Use the code above
2. Open the console to see
3. If the check box is used and bound to multiple records, the warning will be displayed for each row.

### Screenshot

![image](https://user-images.githubusercontent.com/5080143/118463675-f3e54b80-b6f7-11eb-96f0-dd26111be2f9.png)

**Comment by thyhjwb6** [comment]
The warning should be removed in favour of `isChecked` having the `@deprecated` tag which cannot be removed to ensure backwards compatibility.

@cpoDesign use the `checked` prop:

```
          <Checkbox
            checked
            name="nodataCheckBox"
            label="No data"
            onChange={() => console.log('changed')}
          />
```
