### ISSUE TITLE
Select - Clear button should be optional

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#2386]
### Description
https://storybook.royalnavy.io/?path=/docs/select--default

The 'x' button that clears the select should be optional, we would like a way to turn it off, as we currently have mandatory fields using Select which we do not wish to be cleared.

**Comment by m7kvqbe1** [comment]
`NumberInput` currently has the same behaviour toggled by a `canClear` prop. 

Probably worth replicating that behaviour for `2.x.x`.
