### ISSUE TITLE
Docs Site sidebar redesign

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#239]
# Overview
After conducting multiple User Research sessions on the Docs Site, a recurring issue has emerged with the usability of the sidebar. Currently, the active state uses a blue colour to signify the active page in sidebar, however we also use a slightly darker blue to highlight a parent link in the sidebar. This causes the parent link to look active, even when it isn't.

The proposed solution:
- Remove the blue highlight from the parent links to prevent confusion as to what is currently the active page.
- Placing all sub links inside a collapsable menu underneath the Parent link.
- Removing the background to reduce the overall impact of the sidebar

<img width="983" alt="Screenshot 2019-08-22 at 12 10 57" src="https://user-images.githubusercontent.com/48090803/63510362-47504880-c4d6-11e9-8234-7c33f604fd45.png">

**Comment by m7kvqbe1** [comment]
https://github.com/Royal-Navy/standards-toolkit/pull/249

**Comment by hxltrhuxze** [comment]
Closing this ticket as the PR #249 has been merged
