### ISSUE TITLE
More customisable Buttons - Icon only button

### ISSUE THREAD

**Issue by ARChilton** [Royal-Navy/design-system#2394]
### Description
I need to make a button with just an icon.

Normally I would make the button's children the icon but the type restriction of type: string is preventing that.

I have also tried using the icon prop but that adds a margin left or right depending on which position I try.

Would it be possible to slacken the children type to include ReactNodes so anything can be put within the button? or offer an icon-only position option.

Thanks for the great library!

**Comment by k9dh3zij** [comment]
Thank you, this feature will be added in the next release (v3).
