### ISSUE TITLE
Unable to use form components with Formik in 1.1.0 and above

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#241]
The `withFormik` enhancer is not exported with the react component library so users are unable to use the fields in a formik form.

Can we either export `withFormik` or possibly already enhance them and have them as `Formik.TextInput`.

**Comment by m7kvqbe1** [comment]
Good idea - lets export enhanced versions in addition to the enhancer itself.

It appears I exported the enhancer in the wrong index file.

**Comment by m7kvqbe1** [comment]
https://github.com/Royal-Navy/standards-toolkit/pull/245
