### ISSUE TITLE
Type error in Breadcrumb for conditional type (ComponentToUse)

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#244]
**Describe the bug**
TypeScript compiler is throwing a type error that has been temporarily fixed with an any as part of a hotfix: https://github.com/Royal-Navy/standards-toolkit/pull/242

Type error started being thrown when some deps were bumped as part of hotfix (lock file had to be entirely regenerated).

```
// src/components/Breadcrumbs/Breadcrumb.tsx:21:37 - error TS2709: Cannot use namespace 'EndTitle' as a type.
// 21   const ComponentToUse: LinkTypes | EndTitle = last ? EndTitle : LinkComponent
```

**To Reproduce**
Branch from develop and add original type definition in `Breadcrumb.tsx`, line 21.

**Expected behavior**
Correct type definitions declared and no type error thrown by compiler.

**Comment by thyhjwb6** [comment]
Closing this as it was inadvertently fixed with recent interface consistency work.
