### ISSUE TITLE
React hook ESLint rules aren't running

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#2454]
The `react-hooks/rules-of-hooks` and `react-hooks/exhaustive-deps` ESLint rules aren't running in our app. I've created this as a bug as I believe they were running at some point (but I could be wrong so feel free to change this to a feature request).

The reason they aren't running appears to be that [`airbnb/hooks`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnbhooks) is missing from `extends` in `packages/eslint-config-react/index.js`.

### Steps to reproduce

1. Run `yarn lint` in `packages/react-component-library`
2. Observe there are 0 errors
3. Add `airbnb/hooks` to `extends` in `.eslintrc.js`
4. Run `yarn lint` in `packages/react-component-library` again
5. Observe there are now ~10 errors

**Comment by thyhjwb6** [comment]
After investigation this is a larger piece of work and is a feature request so should be a lower priority than other bugs. For now it is possible to work around this by extending the configuration in the application.
