### ISSUE TITLE
Timeline zoom configurable

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#2469]
### Description
Would it be possible to set the max and min level of zoom. 
Backend system may not be able query data for 5 years or performance could be hit when query that much that from a BE system. 

Let me know if you need any more info.

**Comment by thyhjwb6** [comment]
There are two options.

## 1. Max/min
As suggested

## 2. Array of options
Example if you didn't want five year:
```javascript
const options = [
  'hour',
  'quarter_day',
  'day',
  'week',
  'month',
  'year',
]
```

**Comment by c9qsm62x** [comment]
Im leaning towards the array option :)
