### ISSUE TITLE
Delay on first click of navigation item

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#247]
**Describe the bug**
Sometimes when you click an internal link nothing happens or it takes a long time for the new page to load.

**To Reproduce**
Difficult to repro, happens inconsistently.

**Expected behavior**
Immediate navigation to the next page.

**Additional context**

>Trello: it could still be async loading other bundle chunks on navigation (as opposed to downloading the entire site in one bundle) - that might be where the delay comes in.

**Comment by hxltrhuxze** [comment]
Closing due to planned docs site work that will negate this issue.
