### ISSUE TITLE
Improve behaviour consistency between Tab Set, Tab Nav and Masthead Nav

### ISSUE THREAD

**Issue by k9dh3zij** [Royal-Navy/design-system#2482]
There are currently three instances of Tabs/navigation:
- `Tab Set`
- `Tab Nav`
- `Masthead Nav`

**Current behaviour**
- `Masthead Nav` items display a blue highlight bar when the mouse pointer moves over an item (screenshot below), while `Tab Set` and `Tab Nav` don't. 

- `Tab Nav` and `Masthead Nav` items include padding (screenshot below), which is inconsistent with `Tab Set`. 

![image](https://user-images.githubusercontent.com/73531035/123086114-f0419480-d41a-11eb-854c-b9242782def1.png)

**Desired behaviour**

Ensure that `Tab Nav` and `Tab Set` match the `Masthead Nav` behaviour, so that:
- [ ] The blue highlight bar appears when the mouse pointer moves over a nav item

Ensure `Tab Nav` and `Masthead Nav` match the `Tab Set` style, so that:
- [ ] There is no padding around individual nav options
- [ ] There is no padding/margin to the left and right of the navigation bar itself. If a design requires a margin, this should be explicitly defined by downstream designers.

**Comment by k9dh3zij** [comment]
Combined with #2481 as discussed in backlog refinement.

**Comment by thyhjwb6** [comment]
This was created before recent v3 design alignment.
