### ISSUE TITLE
MastheadUser's Floating box A11y aria-dialog-name

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#2509]
### Steps to reproduce
1. Goto storybook.
https://storybook.royalnavy.io/?path=/story/masthead--default
2. Open the Accessibility drawer.
![image](https://user-images.githubusercontent.com/75253719/123629779-9838d280-d80c-11eb-9fa7-1ed7979f17cb.png)

```
Ensures every ARIA dialog and alertdialog node has an accessible name

ARIA dialog and alertdialog nodes should have an accessible name

More info...
.StyledFloatingBox-sc-7xbquf-0.gjcbWv[role="dialog"]:nth-child(4)

Serious
aria-label attribute does not exist or is empty
Serious
aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
Serious
Element has no title attribute
```

**Comment by m7kvqbe1** [comment]
This is a regression that was introduced by a recent major refactor of the positioning engine behind the `FloatingBox` primitive.

This has been resolved as a side effect of https://github.com/Royal-Navy/design-system/pull/2560.

This issue has now been marked as closed.

**Comment by m7kvqbe1** [comment]
Related: https://github.com/Royal-Navy/design-system/issues/2496#issuecomment-874266492
