### ISSUE TITLE
Bug with dialogue / modal window display

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#2598]
Dialogue boxes have a strange border on them as seen in the screenshot. 

Browser was latest version of Chrome.

Our front-end dev informs me this is a component issue.

![Screenshot 2021-07-21 at 12 28 56](https://user-images.githubusercontent.com/52033457/126503503-0e4dab1f-7221-4d5b-9888-63e5a1bd5e2d.png)

**Comment by thyhjwb6** [comment]
Having investigated this it is not easily reproducible. Can you provide a minimal reproduction example and more information about the environment?

**Comment by RichardP932** [comment]
By strange border do you mean the light grey area on the right edge of the dialog close to the submit button? It is a scrollbar which appears not to have rendered and is possibly not required. Are there any other circumstances where modal dialog boxes are shown? If not it is probable that the best solution is to remove the scroll bar. Please advise.
