### ISSUE TITLE
Classification badge

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#2603]
We have a new requirement in our exemplar project to display the classification level of the data.

As discussed with your Product Owner, ideally we'd like a new variant of a badge that looks distinct from the vanilla badge component. It would be great to have badges unique to each classification level whether it be colour or another visual mechanism.

Some of the classification levels are: Official, Official Sensitive, Secret - there may be others.

In terms of placement of this badge it would be great to have some guidance. It may be required to have this in the header or present on every application page, or we may be able to put it in the support modal as per https://github.com/Royal-Navy/design-system/issues/1970. Some options would be great.

Thanks.

**Comment by aavvjg6j** [comment]
Further to my description, security have clarified their position on the placement of the label:

"The expectation to have this classification indication on every page is less aimed at the user (as you rightly mentioned)  but more towards passers-by who could potentially be carrying out their assigned duties around the system (i.e. friendly Journalist taking pictures with no malicious intentions) therefore unintentionally leaking classified information.

A typical example is the word ‘SECRET’ that appears at the top of all URL that users navigate to within <secret> terminals."

We're therefore going to look to place this in the header once you've designed the badge.

Note that the wording in the badge should be uppercase.

Thanks.

**Comment by ghost** [comment]
Hello, has there been any recent update on this?

**Comment by hxltrhuxze** [comment]
@aavvjg6j designs and guidance are available to preview in #2629

**Comment by markhigham** [comment]
Closing. Duplicate of https://github.com/Royal-Navy/design-system/issues/2629
