### ISSUE TITLE
Spacing utility classes do not apply styles with the horizontal and vertical direction modifiers

### ISSUE THREAD

**Issue by jackwry** [Royal-Navy/design-system#2620]
The horizontal (x) and vertical (y) modifiers for the “rn_” styling classes do not apply any margin or padding to the applied components.

This functionality is described in the documentation [here](https://docs.royalnavy.io/styles/spacing).

**Comment by m7kvqbe1** [comment]
This would suggest that you have not imported the relevant generated styles from the package into your application.

Please try the following:

```
import '@defencedigital/css-framework/dist/styles.css'
```

<img width="1247" alt="Screenshot 2021-10-18 at 12 51 34" src="https://user-images.githubusercontent.com/48086589/137725022-80c0d55a-8f53-4bdd-847d-7c9c65ac2506.png">

Note that the css-framework package has been deprecated in favour of design tokens and styled-components. We suggest moving away from this package at your earliest convenience. 

I have marked this ticket as closed, but feel free to respond if this hasn't resolved your issue.
