### ISSUE TITLE
Build Classification Bar

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#2629]
The Classification bar is being created to satisfy the requirement outlined in #2603.

Due to the impact of the banners on screen real estate, only classifications of OS and above should be displayed to the user.

## Masthead
The Masthead has the classification placed above it, and its position will not change regardless of the screen size (e.g. mobile vs desktop):

<img width="810" alt="Screenshot 2021-09-03 16 03 44@2x" src="https://user-images.githubusercontent.com/48090803/132028054-f6d88122-3480-4cb2-b7c3-f779bd56290b.png">

#### Visual treatment

- Official: don't display
- OS: `background: neutral-100` `text: neutral-400`
- Secret and above: `background danger-600`

## Sidebar

The Sidebar has the classification at the top, however the width is scoped to that of the sidebar itself. When the sidebar is collapsed, the classification should also condense itself. On reduced screen sizes, the banner should revert to the top of the page, matching the Masthead.

<img width="877" alt="Screenshot 2021-09-03 16 03 58@2x" src="https://user-images.githubusercontent.com/48090803/132028192-943da11e-2f12-4ee9-b13b-4d22aac272a3.png">

#### Visual treatment

- Official: don't display
- OS: `background: neutral-400`
- Secret and above: `background danger-600`

**Comment by wrengames** [comment]
Is this planned for release to the react-component-library package soon?

**Comment by m7kvqbe1** [comment]
> Is this planned for release to the react-component-library package soon?

@wrengames 

This is indeed on our radar. I can't give you an ETA just yet though.

**Comment by wrengames** [comment]
Thanks for getting this sorted 😊
