### ISSUE TITLE
Expandable panel (accordion)

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#2685]
Hi MOD-uk-design-system team,

We're after an 'expandable panel' or accordion component for our application.

I'm thinking about something like this:
https://material.io/archive/guidelines/components/expansion-panels.html

Have put in a meeting to discuss the design / dev requirements.

Thanks.

**Comment by k9dh3zij** [comment]
Initial design ideas:
https://rw3ydp.axshare.com/#id=qq2l5t&p=intro&g=1

Spec draft:
https://docs.google.com/document/d/1zOxYOzQ6dNeJh2cpHc6qpvzVYPA3qAic8jEurGqMipk/edit

These are **not** final and **not** ready for dev.

**Comment by k9dh3zij** [comment]
Accordion spec:

https://rw3ydp.axshare.com/#id=5lm4qo&p=accordion
and
https://docs.google.com/document/d/1zOxYOzQ6dNeJh2cpHc6qpvzVYPA3qAic8jEurGqMipk/edit?usp=sharing
