### ISSUE TITLE
Text Input Component not holding state

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#271]
**Describe the bug**
After entering text in the Text Input, the input does not hold its filled state. This causes the label to revert back to its `:empty` position, clipping the inputted text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to docs.royalnavy.io/components/forms/input
2. Click on the Develop Tab
3. Enter text into input and then click off to remove focus from the input
4. The label reverts back to its starting position, over the top of the entered text.

**Expected behaviour**
The label does not revert to its default state.

**Screenshots**
<img width="551" alt="Screenshot 2019-09-11 at 18 07 24" src="https://user-images.githubusercontent.com/48090803/64720306-10ac9300-d4c2-11e9-8112-8561b134ea0a.png">

**Comment by antictor** [comment]
Most likely the input needs to be put in a formik form in the docs. The field itself is stateless, it's container provides the value as a prop and handle onChange events to that value
