### ISSUE TITLE
Investigate clunky wrapper border transition in Storybook

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#2760]
## Storybook
![2021-10-29 14 13 16](https://user-images.githubusercontent.com/56078793/139441045-d51fef2f-0030-4afe-9013-52b72c65204b.gif)

## Separate app
![2021-10-29 14 00 29](https://user-images.githubusercontent.com/56078793/139440839-dcbff4e4-3544-4626-a45c-6b8d95861488.gif)

**Comment by jpveooys** [comment]
Closing as this is no longer a problem.
