### ISSUE TITLE
Review the need for font breakpoints and remove if not needed

### ISSUE THREAD

**Issue by k9dh3zij** [Royal-Navy/design-system#2761]
See video example below. When changing viewport size, buttons move about slightly. 

From @jpveooys:

There's a bit of logic in what's called the GlobalStyleProvider that makes small tweaks to the font size depending on the viewport width:
https://github.com/defencedigital/mod-uk-design-system/blob/master/packages/design-tokens/src/tokens/light/breakpoints.json

I agree it's odd (we turned it off in MSP). It's not something visible in Storybook as I don't think the GlobalStyleProvider is loaded there.

This was annoying as different people can be looking at slightly different things, and the modals get taller as the browser gets wider.

https://user-images.githubusercontent.com/73531035/139437276-ca47dba0-1dc1-4f0a-8eae-195820246d86.mov

**Comment by jpveooys** [comment]
@k9dh3zij Just updated the title to be a bit more specific as GlobalStyleProvider does other stuff as well :slightly_smiling_face:
