### ISSUE TITLE
DatePicker: Keyboard date entry fails when using custom date format

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#2766]
### Steps to reproduce

1. Go to https://storybook.design-system.digital.mod.uk/?path=/story/date-picker--custom-format
2. Click in the date picker
3. (Optional) type a new date using the keyboard
3. Click out of the input

A red invalid value border appears around the input.

### Screenshot

![datepicker-custom](https://user-images.githubusercontent.com/66470099/139650368-64cbcf55-34f7-4bac-a56f-57ed1722b421.gif)

**Comment by thyhjwb6** [comment]
This appears to be failing when running `INPUT_MASK.test(value)` which is clear that `2021/01/11` would not pass on regex `/^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/`.

Wondering if running `isMatch(value, datePickerFormat)` is enough.
