### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#286]
# Table Component

The Table component is used to display tabular data.

# Base Tables
From looking at the examples and use cases we have, I’ve split the following section into 2 distinct types of components. As an overview, the Data Table should be used when you want to display a large amount of data that have no to little data visualisation or interactivity associated. The Interactive Table however is much more versatile due to its ability to accept interact-able sub-components.

## Data Table
The Data Table is used to display large amounts of data at once - it’s most appropriately used for feeds and raw data. Each row can be hovered and clicked on, however because of this the table cells containing sub-components are read-only. The Data Table cells can only have a single line of text for each table cell - if a value overflows it should be truncated.

### Condensed Variation
<img width="809" alt="Screenshot 2019-09-23 at 16 31 38" src="https://user-images.githubusercontent.com/48090803/65446596-99b1bb80-de2c-11e9-929f-affa3d11d91c.png">
The condensed variation of the Data Table is used for large amounts of data that need to be displaced at once. It has the narrowest rows of any of the table layouts, ensuring as much information can fit into the available space as possible. 

### Expanded Variation
<img width="901" alt="Screenshot 2019-09-23 at 17 14 32" src="https://user-images.githubusercontent.com/48090803/65446617-a2a28d00-de2c-11e9-9c0f-c6074ac49054.png">
The expanded version of the Data Table has the ability to add richer single-line sub-components to table cells. One or more rows can also be selected with the left-aligned checkboxes.

## Interactive Table
<img width="852" alt="Screenshot 2019-09-23 at 17 21 45" src="https://user-images.githubusercontent.com/48090803/65446642-afbf7c00-de2c-11e9-890b-4b641dff5e9b.png">
The Interactive Table is an expanded table that can contain rich sub-components and interactivity. Each cell can be individually interacted with, allowing for a large range of behaviours to exist within the table. However, due to this the table rows cannot be hovered/clicked as a whole. Excluding visual appearance, this is probably the largest difference between the two Base Table designs. Content inside the table cells can also wrap multiple lines, allowing things like long form text to be displayed fully. The option to concatenate the content is also available for this table type.

## Backgrounds
<img width="873" alt="Screenshot 2019-09-23 at 17 02 11" src="https://user-images.githubusercontent.com/48090803/65446675-c5cd3c80-de2c-11e9-8175-0dd9709f07c2.png">
A subtle background can be added to individual table columns to add hierarchy to the table data. It can be used to indicate secondary data, helping to draw focus to the values in the lighter section. This background cannot be used to vertically "stripe" the table - all columns that have the background should be grouped together and fixed to the right hand side of the table.

## Sub Components
All Tables can accept components within their cells, however how a user interacts with these components depends on the type of base table used. As noted above, the Data Table is used for large amounts of raw data, where the focus is on displaying as much information as possible. Larger sub components that contain interactivity should be used in the Interactive Table.

# Containers
<img width="996" alt="Screenshot 2019-09-23 at 16 38 37" src="https://user-images.githubusercontent.com/48090803/65446714-db426680-de2c-11e9-9f30-6380e2c7ade3.png">
The Tables have the option of either being wrapped in a card-like container or having no exterior border to them. This allows us to place a table in any scenario required.

# Separate Docs Site Section

Much like the Forms section there is an almost infinite way of constructing a table. Due to this I suggest we make another section on our Components page for Tables. This section would outline the basics of the different variations we have and when to use them. We can also include the table specific sub components that can be added.

# Ongoing
Moving forward, adding components to the table will be on as-needed basis. Like with Forms, as the component library expands we should decide which components should be made available in the Table. We will also need to consider how we adapt certain components, as they may need tweaking to suit the table context.

**Comment by m7kvqbe1** [comment]
I've defined an example of the API using some pseudo JSX below.

It shows a declarative way of defining the output and behaviours for each individual column. I've used a [render prop](https://reactjs.org/docs/render-props.html) in order to allow column data to be mapped to arbitrary template components.

```jsx
const data: []TableRow = [{
  foo: 'Hello, World!'
}]

<rn-table 
  caption="Example Table Caption" 
  data={data} 
  borderless 
  selectable
>
  <rn-column 
    label="Example Column 1" 
    render={({ foo }) => (
      <arbitrary-template-component bar={foo} />
  )} />
  <rn-column 
    label="Example Column 2" 
    sortable 
    sortMethod={() => { /* Custom sorting logic */ }} 
    width="300" 
    empty-text="No Data"
    background="#C9C9C9"
  />
</rn-table>
```

## Multiple Implementations

I'm not completely convinced we need to split it into two distinct implementations. Could interactive table not just be used for data table (albeit decorated with less functionality)?

## Striped Columns

>This background cannot be used to vertically "stripe" the table - all columns that have the background should be grouped together and fixed to the right hand side of the table.

This sounds overly restrictive from a developers point of view. I can see there being a use case where you would want to dynamically highlight certain columns.

## Responsive

What are we going to do about mobile? I think these components need to simply scroll horizontally. I don't see any other way of making them work on smaller form factors (without heavily restricting how they are used).

I think the stacking card like table (as seen in the docs-site) should be an additional component (separate from this table implementation).

**Comment by users-champion** [comment]
### **Obvious clickable items**
It's good that cells in the interactive table can be interacted with but an issue has come up in testing where users don't realise that the items in the table are clickable. Relying on hover isn't enough evidenced by user test videos. 

A common use case is to use the table as a home or start point to view a summary of status and actions.  Users want to view the detail and return to the table.   which means there needs to be an obvious way to view underlying detail.   

1)  In the use case above, not every cell needs to be interacted with and in fact it slows the user down if they don't have a clear element to click on to view the underlying detail of each item

2) Some underlying detail could be viewed in the right hand sidebar fly out, but the small side bar isn't big enough for certain types of detail. Some detail takes up a whole screen or even several screens.

3) What are options to make it clear something is clickable?

4) one option is underlining clickable items in tables to make it obvious they were links.  but designers don't like the ugliness of underlined links.  

5) on principal I believe we must put usability before design, whatever the solution is

**Comment by hxltrhuxze** [comment]
@m7kvqbe1 and @users-champion I've added my responses to the points above. Let me know if you have any questions.

## Multiple Implementations
> I’m not completely convinced we need to split it into two distinct implementations. Could interactive table not just be used for data table (albeit decorated with less functionality)?

Yeah, this is a fair point. I was trying to establish a visual difference between Tables that have their entire rows clickable and Tables that only the individual cells (/the content inside the cells) are clickable. You can’t have both a row and a cell clickable in the same table, so having this distinction may help comprehension. I’m happy to combine the table into one, although communicating this difference may need some thinking.

## Striped Columns
> This background cannot be used to vertically “stripe” the table - all columns that have the background should be grouped together and fixed to the right hand side of the table.
> This sounds overly restrictive from a developers point of view. I can see there being a use case where you would want to dynamically highlight certain columns.

1. Dynamically highlighting tables will definitely be useful, however I really wish to stay away from allowing implementers to arbitrarily stripe the backgrounds of table columns. I feel this will cause the background change to lose meaning and just be used as a decorative feature.

## Responsive
> What are we going to do about mobile? I think these components need to simply scroll horizontally. I don’t see any other way of making them work on smaller form factors (without heavily restricting how they are used). I think the stacking card like table (as seen in the docs-site) should be an additional component (separate from this table implementation).

I think we should allow both options - maybe it’s on the implementer to decide which style is most appropriate? I can see use cases for both responsive methods. Sometimes the scrollable table can be hard to digest, especially if there are a large number of columns. Maybe in this instance, presenting each table row as a card may be the better way to convey the data. Either way, I don’t have a preference for a particular style, but perhaps we should offer recommendations as to the best approach for mobile.


### Obvious clickable items
> It’s good that cells in the interactive table can be interacted with but an issue has come up in testing where users don’t realise that the items in the table are clickable. Relying on hover isn’t enough evidenced by user test videos.

Is this specifically for links or for the more visual components? Links are easy to solve as we can add the Link icon to each of those. That’ll at least provide visual separation between default text in the table and links that can be clicked.

Subcomponents I’m unsure how to tackle as we can’t underline them/add a share icon. Hopefully their design will convey if they’re intractable or not. May need to revisit this. 

Hover though is literally the _THE_ interaction on web applications. If users don’t know what to do when they hover on something and get interaction feedback (e.g. transition on hover etc), then we have a much larger problem than the users not understanding how to engage with the table subcomponents. There needs to be some form of education to ensure users understand how to interact with apps in general if this is the case. 

> A common use case is to use the table as a home or start point to view a summary of status and actions. Users want to view the detail and return to the table. which means there needs to be an obvious way to view underlying detail.

This feels like a pattern that is much larger than the table itself. Whilst this is a flow we should definitely be using in our applications, the starting point doesn’t necessarily have to be the Table - it could also be a list, or a set of cards.

> In the use case above, not every cell needs to be interacted with and in fact it slows the user down if they don’t have a clear element to click on to view the underlying detail of each item

We can hopefully tackle this with the icon for links, however there is always  going to be a bit of a learning curve with any new software you use. Yes applications should be as initiative as possible to use, however these apps need room to be powerful tools that are used daily by users. If someone doesn’t get something on their first pass, then let’s obviously look at it. I don’t think that just because they weren’t 100% on their first interaction with the app that the feature/pattern/component is _wrong_. There will need to be learning on both sides. Whilst we should ensure our software is as easy to use as possible, I wouldn’t want to start sacrificing it because a user takes a bit longer to understand stuff on their first exposure.

> Some underlying detail could be viewed in the right hand sidebar fly out, but the small side bar isn’t big enough for certain types of detail. Some detail takes up a whole screen or even several screens.

Yeah this is a pattern to define at a higher level. What sort of flows do we want the user to have when using our applications? 

> What are options to make it clear something is clickable?
We can add the link icon to anchor text, however individual subcomponents will have to be looked at on a case-by-case basis.

> One option is underlining clickable items in tables to make it obvious they were links. but designers don’t like the ugliness of underlined links.

As I commented above in this post, hopefully the inclusion of an icon next to clickable text should hopefully mitigate this problem.

> on principal I believe we must put usability before design, whatever the solution is

I certainly don’t believe these are mutually exclusive at all - we should be striving for both :)

**Comment by ghost** [comment]
I don't feel this needs 'sign off'. There's a great amount of discussion in here and I like the approach (discussed in person) of building it incrementally (starting small) and also of getting feedback as we go. 

I also like the idea of a separate area within the doc site to allow for some of the variations to be illustrated properly. It would be good to see that appear as part of the first built iteration rather than waiting for more table functionality to be implemented.

**Comment by hxltrhuxze** [comment]
Breaking this down for a first pass at building it, I imagine the easiest route would be to construct a table that either accepts an array of data or an arbitrary component (e.g. badges). We should make it responsive, with the table horizontally scrolling at smaller screen sizes.

Sortable headers, table specific sub-components, and the stackable cards can come at a later iteration.

@Royal-Navy/standards-team Is there anything else we should add/omit for v1?

**Comment by ghost** [comment]
Found a pattern request from Project L, which asks for "Table Totals". Rather than lose it or create it's own component / pattern issue, I thought I'd add it here because the requirements are just more advanced features of the table:

**Table Totals**
- Self service analytics
- Present counts, sums, averages, etc.
- Calculate and present percentages
- Calculate and present totals

**Comment by thyhjwb6** [comment]
The basic table component is done and there are also PRs for arbitrary cell content and sorting.
