### ISSUE TITLE
Look at 1px label movement caused by outer wrapper update

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#2889]
Recent changes to the `StyledOuterWrapper` mean that elements have moved by 1px. This needs reviewing with @k9dh3zij and updating affected elements.

[Chromatic example](https://www.chromatic.com/build?appId=5e25c277526d380020b5e418&number=4326)

This issue needs to include resolving issues around label align across all browsers.

## Label alignment issues
![image](https://user-images.githubusercontent.com/56078793/145381891-f904f079-5f01-4139-9150-a03f4247f701.png)
![image](https://user-images.githubusercontent.com/56078793/145381928-8e3f1bad-b245-40af-a182-8188c058a15e.png)

**Comment by jpveooys** [comment]
Also note:

The button left border for DatePickerE and NumberInputE does not fill the container:

![](https://user-images.githubusercontent.com/73531035/145382651-a1da7678-4013-445a-b8ba-26282cd1e422.png)

**Comment by k9dh3zij** [comment]
@jpveooys @thyhjwb6 

It seems that the border updates have messed up input heights, and this may be related?
TextInputE is also 52px tall, NumberInputE is 50px tall etc. They should all be 46px tall.

![image](https://user-images.githubusercontent.com/73531035/146000346-11a88e97-eb93-4907-a2bf-1b146007e07c.png)
