### ISSUE TITLE
Select / drop-down overflow bug

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#2951]
When a select element contains text that does not fit it overflows the component, blocking the "X" and drop down icon.

I'm not sure how you would want to fix, but some kind of truncation and tooltip combination could work.

![bug](https://user-images.githubusercontent.com/52033457/148243985-398edcac-bd7d-49c7-9f16-79566f81fec9.jpg)
.

**Comment by c9qsm62x** [comment]
Code to reproduce
https://codesandbox.io/s/nervous-bas-d4uzm
