### ISSUE TITLE
Allow typing and pasting negative numbers into NumberInputE

### ISSUE THREAD

**Issue by k9dh3zij** [Royal-Navy/design-system#2967]
Currently NumberInputE won't let me type in or paste a negative number. However using the buttons, it does go to negatives, so I'm assuming we are disallowing '-', which we shouldn't.

**Comment by jpveooys** [comment]
I made a start on this on this branch: https://github.com/defencedigital/mod-uk-design-system/tree/bugfix/number-input-e-negative
