### ISSUE TITLE
Docs-site Sidebar navigation hoisting nested items

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#299]
**Describe the bug**
The sidebar navigation sometimes fails to nest some page links.

**Expected behavior**
Nested sidebar structure is representative of content library directory structure.

**Screenshots**
Note how the Checkbox item is not nested within forms despite it existing within that directory.

<img width="160" alt="Screenshot 2019-09-27 at 12 18 40" src="https://user-images.githubusercontent.com/48086589/65765732-f826b480-e120-11e9-922c-32a017306d3a.png">

**Additional context**

May be something to do with when the files were last touched. I'm able to fix it by moving the files out of the nested directory and then back into it.

----

I wrote a recursive function to generate a tree of page objects based on URL structure:

https://github.com/Royal-Navy/standards-toolkit/blob/develop/packages/docs-site/src/utils/nav.js#L48

There might be an easier way to do this (i'm surprised Gatsby doesn't provide this).

----

There are some hooks used by the sidebar and main navigation that need refactoring:

https://github.com/Royal-Navy/standards-toolkit/tree/develop/packages/docs-site/src/hooks

These have evolved into a mess over time as requirements have changed.

**Comment by hxltrhuxze** [comment]
Closing due to planned docs site work that will negate this issue.
