### ISSUE TITLE
Tidy up legacy packages

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#300]
## Legacy react-component-library
The legacy `react-component-library` package can now be removed from the codebase.

## vue-component-library
The `vue-component-library` should be moved to the deprecated directory:
   - Remove all related jobs from CI config
   - Move files to deprecated folder
   - Request removal from NPM registry

## Additional notes

Deprecated probably isn't the best name for this directory. It's acting as a 'graveyard' within the monorepo while we continue to migrate legacy components over to new implementations.

**Comment by antictor** [comment]
Lets pull the vue ones out to a separate repo
