### ISSUE TITLE
Load correct fonts once from canonical source and use GlobalStyleProvider in Storybook

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#3006]
- The font package and fonts.googleapis.com are both being used to include fonts within Storybook.

- It also looks as though the `GlobalStyleProvider` isn't being utilised.

- There seems to be a flashing of an italic font in the new `Autocomplete` implementation. Investigate the use of `font-display: swap`.

- The `Breadcrumbs` component also seems to have alignment issues with a `700` weight font on some browsers and operating systems.

**Comment by jpveooys** [comment]
The Breadcrumbs last item alignment problem can also be seen in the snapshots on Chromatic:

- [recent Chrome snapshot of Breadcrumbs](https://www.chromatic.com/component?buildNumber=4695&historyLengthAtIndex=14&distanceToMoveBack=-11&appId=5e25c277526d380020b5e418&name=Breadcrumbs&componentInspectorKey=61ea35826e7907003a0a50ab-1200-snapshot-true-chrome)

We may also be able to remove `@storybook/preset-scss` and `@storybook/addon-postcss` if the dependency on the CSS framework is removed.
