### ISSUE TITLE
Fixup ESLint warnings

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#302]
There appear to be a large number of ESLint warnings:

<img width="1422" alt="Screenshot 2019-09-27 at 12 47 55" src="https://user-images.githubusercontent.com/48086589/65767210-1a223600-e125-11e9-9c7a-d69f51d60702.png">

It may be that our lint config needs a little bit of tweaking.

Most of them appear to be regarding console.log (Storybook stories) and explicit any type usage.

**Comment by antictor** [comment]
The thing is we want to be warned about 'any' usage as it encourages us to fix it, but there are times we need it
