### ISSUE TITLE
Date Picker overflow is not handled when the component is small

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#3217]
Hi we are using this component in a drawer component where the space is compact
![image](https://user-images.githubusercontent.com/75253719/160855346-4cc4e1eb-4680-49b9-a3b5-3111ada734bc.png)

**Comment by jpveooys** [comment]
Additionally, this affects other components such as TextInput when they have a long label:

![image](https://user-images.githubusercontent.com/66470099/161226247-acf3e3c1-bd56-40e9-a453-cab6b12bbc7e.png)

![image](https://user-images.githubusercontent.com/66470099/161226182-104902ce-b62f-4856-b7ae-e4933947b4e3.png)

The small label would fit in some cases but the width is being reduced.
