### ISSUE TITLE
Checkbox with no container focus style is too subtle

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#3256]
Hi first of all thank you for your help with the previous issues. It is appreciated. 

I noticed that focus style on the Checkbox with containers is very subtle. Could we have a border?
<img width="796" alt="Screenshot 2022-04-25 at 16 42 22" src="https://user-images.githubusercontent.com/75253719/165266107-4af5defb-248d-43d9-9277-1dcdc5ef739a.png">

**Comment by m7kvqbe1** [comment]
This does seem like a sensible request - I have also picked up on this previously.

I will check the original spec and discuss with the wider team.
