### ISSUE TITLE
Add GlobalStyleProvider singleton check to prevent use more than once within a consuming app (parallel and nested)

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#3259]
Storybook is a good example of where this is a problem.

Individual stories are decorated with the provider. 

In the docs tab these are rendered inline within a single iframe. 

The result is duplication of global styles.

---

Find a way of ensuring only a single instance of the `GlobalStyleProvider` can exist at any one time within a React tree. 

Possibly also add a warning if it's not the root node.

---

See this ticket for relevant comments: https://github.com/defencedigital/mod-uk-design-system/pull/3258

**Comment by jpveooys** [comment]
We decided to fix the problem directly in Storybook, where it was observed, rather than trying to apply a more generic fix, as discussed here: https://github.com/defencedigital/mod-uk-design-system/pull/3307
