### ISSUE TITLE
Migrate to pnpm

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#3267]
Following https://github.com/defencedigital/mod-uk-design-system/issues/2716 we decided that we should migrate from yarn v1 to npm v8.

There are currently two external issues blocking this:

- https://github.com/npm/cli/issues/4834
- https://github.com/lerna/lerna/issues/2832 (assuming that this affects us)

A chunk of the work has already been done on this branch: https://github.com/defencedigital/mod-uk-design-system/tree/spike/npm-v8-2

**Comment by jpveooys** [comment]
As yet, the linked npm issue remains unresolved. [pnpm](https://pnpm.io/) is an alternative that could be investigated.

**Comment by jpveooys** [comment]
Unfortunately, using pnpm is also blocked, as Dependabot does not support it:

- https://github.com/dependabot/dependabot-core/issues/1736

Some initial work on using pnpm is on this branch:

https://github.com/defencedigital/mod-uk-design-system/pull/new/chore/pnpm

**Comment by markhigham** [comment]
pnpm
