### ISSUE TITLE
React 18 causing Defence Digital CRA template to fail loading

### ISSUE THREAD

**Issue by Redtigercod4** [Royal-Navy/design-system#3270]
### Steps to reproduce
1. npx create-react-app my-app --template defencedigital
2. npm start

### Minimal reproduction

When cloning the CRA template, after running up the site. The home page fails to render with the terminal showing invalid hook calls and the outdated render method. I have updated the render method to typescript with the following code. 
The other issues, I haven't been able to trace through to libraries.

https://github.com/Redtigercod4/Defence-Digital-CRA

### Screenshot
![Defence Digital Error](https://user-images.githubusercontent.com/76014409/167162191-0e781735-41f7-4ae3-8d2b-86f7c97134b0.png)

``` const container = document.getElementById('root')
    const root = createRoot(container!)

**Comment by jpveooys** [comment]
I had a quick look and the hook error is due to multiple versions of React in the dependency tree (due to React 18 not being in some packages' peer dependency range).

A quick workaround should be to:

1. Update npm to the latest version (currently 8.9.0)
2. Add:

    ```
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
    ```

    to the `overrides` key in package.json
3. Run `npm install`
