### ISSUE TITLE
NumberInput has no ability to display prefix (currency)

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#338]
NumberInput has no ability to display prefix (currency).

The Coffee app mocks show a '£' symbol to the left of the input.

This is a new requirement.

**Comment by hxltrhuxze** [comment]
I probably should've used a `pre-fix` with the £ symbol inside it:

<img width="745" alt="Screenshot 2019-10-17 at 17 19 48" src="https://user-images.githubusercontent.com/48090803/67027933-5cc2a700-f102-11e9-9fbb-dd8b02051a45.png">

Having said that, it might be useful to add the ability to have characters to the left of the input value
