### ISSUE TITLE
TextInput component example provided within standards fails to compile

### ISSUE THREAD

**Issue by MercatorSunday** [Royal-Navy/design-system#343]
**Describe the bug**
The [TextInput component example](https://docs.royalnavy.io/components/forms/input) within the standards documentation fails to compile due to an 'Invariant Violation'.

**To Reproduce**
1. Go to https://codesandbox.io/embed/textcomponent-rz400
2. Select 'Click to run'

NB - I have slightly modified the standards example, the opening `<Formik>` tab has had its attributes removed for conciseness.  As `import` statements are not included in the standards, I have followed defaults in [Formik documentation](https://jaredpalmer.com/formik/docs/overview).

For comparison I have written the same code, but with the RN specific TextInput components commented out, and this compiles correctly:
https://codesandbox.io/embed/textcomponentnonrn-uswnz

**Expected behaviour**
The page should compile showing input boxes as featured in the documentation.  

**Screenshots**
See link.

**Desktop:**
 - OS: Ubuntu 18.04 LTS
 - Browser: Firefox Quantum 69.0.2

**Additional context**
If page fails to compile due to my choice of imports, i.e:

`import { Formik, Form, Field } from "formik";`
`import { TextInput, Search } from "@royalnavy/react-component-library";`

then it is requested that a Minimal, Reproducible Example is included within standards documentation

**Comment by antictor** [comment]
The documentation for TextInput is out of sync with the changes made to support Formik and non-Formik forms. Updating the documentation to address this.

**Comment by antictor** [comment]
Updated example here

https://codesandbox.io/embed/textcomponent-ytrk3

There is a small error in the documentation recently added to  https://docs.royalnavy.io/components/form , which will be corrected, and the documentation for the TextInput component will also be updated

**Comment by MercatorSunday** [comment]
> Updated example here
> 
> https://codesandbox.io/embed/textcomponent-ytrk3
> 
> There is a small error in the documentation recently added to https://docs.royalnavy.io/components/form , which will be corrected, and the documentation for the TextInput component will also be updated

Thank you.  I'm still getting the error on the updated codesandbox example you provided above, see screenshot attached. Is this because https://github.com/Royal-Navy/standards-toolkit/pull/382 hasn't gone through yet, or am I doing something wrong?

![formik](https://user-images.githubusercontent.com/56444093/67244175-15654f00-f451-11e9-8483-2ca8f24f9446.png)

**Comment by antictor** [comment]
https://codesandbox.io/s/textcomponent-ytrk3?fontsize=14

**Comment by antictor** [comment]
import {
  Formik as FormControls,
  Icons
} from "@royalnavy/react-component-library";

const { TextInput } = FormControls;
const { Search } = Icons;

**Comment by MercatorSunday** [comment]
Spotty dog.  It works.  VMT.
