### ISSUE TITLE
Card Frame Component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#345]
## Description

A styled container with no state or props. in the future we'd augment this component with other subcomponents (headers, footers, content, etc.). This differs from the panel component. Google describe this as a "container for a single subject".

## Component classification

This component is an Atom.

## Details / user needs

- Can take any JSX

## Questions

Outstanding questions for the Product Owner, Designers or Developers.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
The Card Frame is a very simple component designed to wrap all cards. 
<img width="348" alt="Screenshot 2019-10-28 at 17 06 27" src="https://user-images.githubusercontent.com/48090803/67700176-615e4980-f9a5-11e9-9042-67d640660017.png">

Its styles are:
```
border-radius: 3px;
background-color: color("neutral", "white");
box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
```

**Comment by ghost** [comment]
This just needs dev effort.
