### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#347]
## Description

An animated indication that some form of network request or processing pending. 

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details / user needs

- Need to be able to do it on a component.
- Need to be able to do it on a complete page.

## Questions

- Would we have an optional text label?
- @aavvjg6j - any other needs for the spinner from projects?

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
SVG spinner that can be used as a loading animation either on a component or a full screen.

https://jsfiddle.net/0kdjx4h8/1/

**Comment by m7kvqbe1** [comment]
LGTM

**Comment by hxltrhuxze** [comment]
Loading spinner component sits full screen with `Loading...` underneath the animating spinner.

<img width="443" alt="Screenshot 2020-03-10 at 13 55 04" src="https://user-images.githubusercontent.com/48090803/76319358-01729a80-62d7-11ea-8088-8c671cf75462.png">
