### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#348]
## Description

A draw sliding out from the right hand side. 

## Component classification

This component is an atom.

## Details

- Animates open and close
- Some means of opening and closing the drawer
- Independently scrolling drawer content
- No fade for the rest of the screen
- Should stick over all other content
- Not on mobile
- Documentation explicit about differences to side navigation, etc.

## Questions

Outstanding questions for the Product Owner, Designers or Developers.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
The Drawer component is a simple panel that can be triggered to appear on the right hand side of the screen. This current version only contains the shell and close button.

The Drawer should animate from off screen and slide in to the right of the window.

<img width="324" alt="Screenshot 2019-11-04 at 15 49 59" src="https://user-images.githubusercontent.com/48090803/68137200-7e9f9480-ff1e-11e9-9f42-bc5fa1669f45.png">

**Comment by ghost** [comment]
A couple of observations/questions:

Will we recommend:
- how far it should come out?
- how quickly it comes out
- how quickly it goes back when x is clicked?
and do the devs need to know that stuff to implement it?

Will a user be able to scroll vertically within the card. Here's an example of what I mean:
- Go to the Standards Tactical Roadmap
- Click on the title of one of our cards
- Scroll up and down inside the thing on the right (I'm assuming that's a drawer?)

**Comment by hxltrhuxze** [comment]
#### how far it should come out?
This is tricky - I'd like to avoid dictating sizes for this as there may be multiple use cases that require different sizes. For a rule of thumb though, I think the Drawer should never occupy more than `33.33%` of the width of the page.

#### how quickly it comes out?
We try to keep all animations to a maximum of `0.3s`.

#### how quickly it goes back when x is clicked?
Should also be `0.3s` - it's simply reversing the animation that brought it out.

#### Do the devs need to know that stuff to implement it?
We have basic animations already in the project and this should follow suit. This'll be something we'll have to work with the devs on though, as it'll take a working example to test what sort of animation timing curves we use.

#### Will a user be able to scroll vertically within the card?
Yeah absolutely. Very much like the behaviour of the GitHub Drawer on the project boards.
