### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#349]
## Description

It's a way to communicate events / information to a user. 

## Component classification

This component is an atom.

## Details / user needs

- Display a title, message and severity
- Needs to be dismissed by the user
- Displays within the flow of the page (not a toast).

## Questions

Outstanding questions for the Product Owner, Designers or Developers.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Alert Component

The Alert Component has 4 variations - Info, Danger, Warning, and Success. Each can be dismissed by clicking the x in the top right hand corner. There is the option to supply a Title and Description, or just a Description to the component.

<img width="1175" alt="Screenshot 2019-11-06 at 10 56 23" src="https://user-images.githubusercontent.com/48090803/68292608-24204880-0084-11ea-8a60-89c8e09407b1.png">

**Comment by ghost** [comment]
We've discussed some work about colour-blindness. With the changes that will come from that, it gets sign-off from me. Out of interest, is the positioning of the alert in the window at the discretion of the developer/designer?

**Comment by hxltrhuxze** [comment]
Updated the designs to include identifying icons from our icon library:

<img width="1201" alt="Screenshot 2019-11-06 at 11 46 29" src="https://user-images.githubusercontent.com/48090803/68295815-1de19a80-008b-11ea-8d52-f79c2618b418.png">


Regarding positioning: These Alerts sit within the flow of the document, so yeah they are at the discretion of the designer/developer using them.
