### ISSUE TITLE
Panel Component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#351]
## Description

Styled container for visually separating content. 

## Component classification

This component is an atom.

## Details / user needs

* Can take any JSX

## Questions

Outstanding questions for the Product Owner, Designers or Developers.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by hxltrhuxze** [comment]
# Panel Component

The Panel Component is a simple container used to group content. It is similar to the card component, but can accept arbitrary content.

<img width="668" alt="Screenshot 2019-11-04 at 14 29 43" src="https://user-images.githubusercontent.com/48090803/68128408-93c0f700-ff0f-11e9-9cc8-7413d2049c6c.png">
