### ISSUE TITLE
Data List Component

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#352]
## Description

A list of labels and their associated values. A way of representing a single record.

## Component classification

Is this component an atom, molecule or organism?
- [x] Atom
- [ ] Molecule
- [ ] Organism

## Details

- Vertical and horizontal layouts

## Variations

Any alternative or state driven variants of the component, such as an 'inactive' state.

## Questions

Outstanding questions for the Product Owner, Designers or Developers.

## Definition of done
- [ ] The Sketch file is updated with the component
- [ ] There are screenshots of all component variations in this ticket
- [ ] All states are included if applicable (default, hover, active, focus)
- [ ] A design documentation PR is linked from this ticket
- [ ] All questions laid out in this ticket have been resolved 
- [ ] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by el7h1rw2** [comment]
Added "Requires Discussion" as we're using this component request as a test case to help define our process. We will be producing our own version of this - https://bradfrost.com/blog/post/a-design-system-governance-process/
