### ISSUE TITLE
DatePicker - Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#3528]
### Steps to reproduce
1. Create a new application using the CRA template
2. Add `DatePicker` inside `React.StrictMode`
3. Start application
4. Open `DatePicker` sheet and view the console

### Screenshot
<img width="746" alt="Screenshot 2022-11-25 at 16 05 05" src="https://user-images.githubusercontent.com/56078793/204022033-5199f449-2825-4eea-9305-172fc1e584ac.png">

**Comment by jpveooys** [comment]
Hi @thyhjwb6 :wave: 

There was a fix for this in version 9.0.0 or newer of focus-trap-react: https://github.com/focus-trap/focus-trap-react/issues/77

However, we're unable to update at the moment as it would break support for older browsers (which would be a breaking change).

**Comment by oliverrees** [comment]
+1 for this issue!

**Comment by markhigham** [comment]
Revisiting this as legacy browser support requirements have changed

**Comment by jpveooys** [comment]
Should be fixed by https://github.com/Royal-Navy/design-system/pull/3964
