### ISSUE TITLE
Label text is not vertically middle for `Autocomplete` and `Select` in Firefox

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#3543]
The label text is 1px away from being in the middle in Firefox browser.

### Screenshot
<img width="532" alt="Screenshot 2022-12-07 at 14 12 52" src="https://user-images.githubusercontent.com/56078793/206201907-ca65176f-62dd-4ec9-ac43-9ccfe38935f5.png">

**Comment by jpveooys** [comment]
Similar to #3544 , the positioning is dependent on the combination of font, browser and OS.

Firefox on Ubuntu 22.04:

![image](https://user-images.githubusercontent.com/66470099/206233538-c7072868-b664-435d-b8a6-faf67781070d.png)

Firefox on Windows 10:

![image (5)](https://user-images.githubusercontent.com/66470099/206233393-c23551d8-02ea-4029-b894-4b1b7f8f8704.png)

Have assigned this the same size.
