### ISSUE TITLE
Add a link to Standards-toolkit Github page

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#358]
**PO Guidance**:
- I think we should proudly show off the fact our source is open. I'd like to see us do that with a Github icon and link in the header and/or footer.
- I think the link should also be easily available in the getting started documentation when it's needed, so ensuring it's linked to there would be good.
- I didn't see any feedback about a link to creating a Github issue, but I wonder if that's something we want to add into our Beta banner?

**Team discussion from user feedback analysis**:

> I feel this is more of a developer rather than a designer ask. One of the developers just wanted to see this quickly, so I feel it should be added to the ‘getting started’ or ‘getting-started/development’ pages. In terms of style, this could be a large icon style button.
> 
> If developers must use github, I suggest you add an obvious link to github in the header/footer.  Otherwise a link in get started should suffice.  
> 
> Is NELSON github an essential ‘partner’ to the standards website? 
> 
> I feel we should make the GitHub link prominent and in the header. We can keep it as an Icon (which generally feels like the accepted way of linking to GitHub). Whilst it only technically applies to Developers, we are an Open Source project so really should be advertising that our code is free to download on GitHub.
> 
> I like the approach taken on the React website: https://reactjs.org (notably the icon denoting that it is an external link).
> I’m also a big fan of including the version number up there - but maybe this is unnecessary clutter. 
> 
> Linking versions not needed. As a developer I want there to be a Github link I can easily see and use. I like the approach that often shows links to Twitter/Github etc together and using the Github icon as that is quicker and easier to see and pick out than words only.
>

**Comment by thyhjwb6** [comment]
This has now been released.
