### ISSUE TITLE
Issue with JSX Pragma in react-toast-notifications

### ISSUE THREAD

**Issue by oliverrees** [Royal-Navy/design-system#3701]
### Description
When integrating `react-toast-notifications` into a Next.js project, an error occurs related to JSX pragma. The error message is `pragma cannot be set when runtime is automatic`. This issue seems to arise from the JSX pragma (`/** @jsx jsx */`) used in the library, which conflicts with the automatic runtime setting of JSX introduced in React 17 and utilized by Next.js.

### Steps to Reproduce
1. Use `create-next-app` to set up a new Next.js project.
2. Install the design system and include `<GlobalStyleProvider/>` on the default `page.tsx`
3. Run the Next.js application using `npm run dev`
4. Observe that a build error occurs, pointing to the JSX pragma in `react-toast-notifications`.

### Screenshot
![Screenshot 2023-12-11 at 12 51 58](https://github.com/Royal-Navy/design-system/assets/5574826/976b0a0f-2c98-498f-864f-77a8af51b950)

### Proposed Solution
Given that `react-toast-notifications` appears to not be actively maintained, and its compatibility issues with modern React and Next.js setups, I propose moving away from this library. The suggested alternative is `react-hot-toast`, which is actively maintained and designed to work with the latest versions of React and Next.js. Transitioning to `react-hot-toast` would not only resolve the current issue but also ensure better support and compatibility in the future.

Alternatively forking `react-toast-notifications` and removing the `/** @jsx jsx */` line solves the issue, which is what I've done in the meantime.

**Comment by m7kvqbe1** [comment]
Thanks @oliverrees - this is on our radar. We'll hopefully have this sorted soon.

**Comment by m7kvqbe1** [comment]
We have now removed reliance upon the unmaintained library utilised by the Toast component.

This change was shipped in the latest major release (https://github.com/Royal-Navy/design-system/commit/e1d5a000ac504fc98fca5fa21189740337ab788b).

I have marked this issue as closed.
