### ISSUE TITLE
Add description of atomic design taxonomy to docs.royalnavy.io

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#371]
**Is your feature request related to a problem? Please describe.**
We use the terms atom, molecule and organism in our issue tracking to help us understand the complexity of a component. But we haven't publicly defined those terms. 

**Describe the solution you'd like**
A clear public explanation / definition of the terms we use to describe components, ideally linked back to the some of the original atomic design thinking.

**Questions / considerations:**
- [ ] Where in the site would that be?
- [ ] Is it just a text explanation or do we illustrate?
- [ ] Can we point to specific examples in our code base to illustrate?
- [ ] Would we ever want to include a label/pill on our component docs pages which shows whether it's an atom, molecule or organism?
- [ ] Explain where patterns fit into this.

**Comment by hxltrhuxze** [comment]
Closing as this naming doesn't match our current conventions of Style, Component, Pattern, and Framework.
