### ISSUE TITLE
Sortable table appears with a line break

### ISSUE THREAD

**Issue by oliverrees** [Royal-Navy/design-system#3713]
The sortable table component is meant to look like the below (as specified in [storybook](https://storybook.design-system.navy.digital.mod.uk/?path=/docs/table--default)).

![Screenshot 2024-01-15 at 15 16 11](https://github.com/Royal-Navy/design-system/assets/5574826/c62246c2-e7ca-42bc-80bf-8ce2d545f173)

However, when you use a vanilla installed version of the design system and copy and paste the code example, the table headings appear with a line break between the text and the sorting arrows (see below)

![Screenshot 2024-01-15 at 15 14 55](https://github.com/Royal-Navy/design-system/assets/5574826/623f0373-0ba8-4666-9dd1-412e69c4f383)

To reproduce:

1. Start with a vanilla version of the design system (I'm using create-next-app)
2. Copy and paste the storybook example from above

**Comment by m7kvqbe1** [comment]
I wonder if there are some global styles or style bleed causing this?

We haven't been able to reproduce it ourselves. Are you able to create a minimal reproduction for us?

Note we are currently implementing a DataGrid that will have feature parity with the table and is intended to supersede it.

**Comment by m7kvqbe1** [comment]
We've just shipped the new DataGrid and deprecated Table.

Please consider upgrading to that.
