### ISSUE TITLE
Design System Tokens - what are they?

### ISSUE THREAD

**Issue by dboycepa** [Royal-Navy/design-system#3727]
### Steps to reproduce

1. Go to https://design-system.navy.digital.mod.uk/tokens 
2. Look (in vain) for any description of what a Token is.  It tells us what they are provided for, but provides no context for understanding what they are.

### Minimal reproduction

N/A

### Screenshot

![image](https://github.com/Royal-Navy/design-system/assets/122276145/f1dea626-0d1b-49bd-ab63-b09925b5a19e)

**Comment by m7kvqbe1** [comment]
Probably best taking a look at the README within the package here:

>An agnostic way to store variables such as typography, color, and spacing.

https://github.com/Royal-Navy/design-system/tree/master/packages/design-tokens

We're looking into the state of the content on that documentation site.

It's got issues with dead-links and missing content at the moment.

**Comment by m7kvqbe1** [comment]
Closing this for now - but feel free to open a GitHub discussion if you'd like more help:

https://github.com/Royal-Navy/design-system/discussions
