### ISSUE TITLE
The Getting Started journeys taken by different types of users needs to be clearer

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#374]
Users used to the GOV.UK [prototyping toolkit](https://govuk-prototype-kit.herokuapp.com/docs), think this is a kit - make it clear Nelson are not providing a toolkit.

We need to discuss how we'll approach this.

**Done when:**
we've re-tested with users and feedback indicates the journeys and expectations for the toolkit are clear to a range of users with different experience.

**Other discussion following feedback:**

I think that one of the main issues here is the approach that gov designers are used to i.e. using the gov prototyping kit to build HTML prototypes, not Sketch. We need clear information on the NELSON design approach i.e. prototype apps using the sketch toolkit, develop apps using the developer toolkit. Once this is cleared up then the journey for designers should be easier. This information could go on the ‘getting started’ page, under the heading ‘Designing NELSON applications’ or similar. We could allude to this methodology on the homepage.

Developers did not seem to have the same confusion in terms of the ‘getting started’ guide, and immediately looked for code snippets and a Github link. That said, the developer sections on the components pages were not noticed.

**Suggestions:**
- Add NELSON process steps - e.g.
- Create designs using the sketch toolkit - more on this
- Develop code using the developer toolkit 
- Use deployment framework
- Use testing framework
- Add more user roles: ‘Designer’, ‘Developer’, ‘Content manager/copywriter’,  ‘Other’
- Show the user what journey they are in at all times

**Developer journey**
Whenever I look at a new framework for the first time, I always look at getting started / introduction. I need something that says 'this is how to create the equivalent of a hello world application, using this tool.

It feels to me like are overarching usage of the word ‘toolkit’ makes more sense and the GOV.UK stuff is misleading - I think we should be careful we don’t make changes that make it clearer for a small minority of users but make it more confusing or content unnecessarily verbose for the wider majority.

What we are building is a toolkit. We are providing tools for both designers and developers to build quality web applications. I worry we’re focusing too much on what GDS are doing, however their use case is entirely different to ours. We’re not the GDS for the Navy - our applications are far more complicated.

The getting started is a part of the website I think could do with the most work and is the first thing I would goto as a developer. I think we need to create a quick version that explains what is is and how to add the npm libraries and another that gives a step by step walk-through of creating a simple hello world app with the library.

I’ve also suggested we start to write articles and videos that walk through how a technology works and constructs a simple example with the user.

**Comment by hxltrhuxze** [comment]
Closing this as it will be superseded by `v2` of the docs site.
