### ISSUE TITLE
Remaining user feedback suggestions

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#377]
We haven't ticketed all the user feedback suggestions to keep the backlog manageable. I've left comments in the document. We'll revisit [this document](https://docs.google.com/document/d/1LLWLaOhrVQHN6rh4MPSsinMrojyZ8sts_Xmp_W9qRBQ/edit) and add extra tickets.

**Comment by hxltrhuxze** [comment]
For awareness: This feedback is from the first iteration of the docs site. Nothing to action on - feedback is still useful for new docs redesign though.
