### ISSUE TITLE
Some props and controls missing from Storybook

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#3838]
I noticed that a lot of the prop documentation and controls have disappeared from Storybook.

For example, if you go to https://storybook.design-system.navy.digital.mod.uk/?path=/docs/components-text-input--docs there are only four props shown (without any descriptions):

![image](https://github.com/Royal-Navy/design-system/assets/66470099/ad468839-c654-4951-b068-60cd47cac6e5)

However, the component has many other props:

https://github.com/Royal-Navy/design-system/blob/e3654d211b8d2417a70ef09dfb0bc14bd8786153/packages/react-component-library/src/components/TextInput/TextInput.tsx#L30-L85

IIRC the prop descriptions were pulling through previously as well.

**Comment by m7kvqbe1** [comment]
Hmm yeah this seems to be broken in a few places we will have take a look asap.
