### ISSUE TITLE
Move all build stages into Circle (instead of Netlify)

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#385]
@m7kvqbe1 - to complete.

**Comment by m7kvqbe1** [comment]
I've just investigated this and moving deploy previews into Circle and deploying to Netlify via their CLI tool would mean we'd have no way of easily obtaining the autogenerated preview URL.

We'd lose some of the magic of Netlify and end up using it in much the same way as Firebase.

**Comment by m7kvqbe1** [comment]
Closing this for now.

**Comment by ghost** [comment]
This is now a spike, attempting to answer the question: Will other platforms allow us to do branch deployments? Starting with AWS, but moving to GovPaas if we can't use AWS.
