### ISSUE TITLE
Group: Incorrect default value for align prop in docs

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#3876]
## Description

The docs state that the default value for the `align` prop of the `Group` component is `center`:

https://github.com/Royal-Navy/design-system/blob/e40ab6c59d691186f24633b83fe6adf3f850f6fa/packages/react-component-library/src/components/Group/Group.tsx#L20-L23

However, the actual default is `stretch`:

https://github.com/Royal-Navy/design-system/blob/e40ab6c59d691186f24633b83fe6adf3f850f6fa/packages/react-component-library/src/components/Group/Group.tsx#L69

**Comment by m7kvqbe1** [comment]
I will quickly change this now to center - it's only us using it at the moment.
