### ISSUE TITLE
DatePicker floating box does not display when React Strict Mode is enabled

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#3907]
### Steps to reproduce

1. Enable React StrictMode
2. Add DatePicker to application
3. Attempt to open the picker

Possibly a problem with FloatingBox and/or FocusTrap.

![Screenshot 2024-10-07 at 12 59 00](https://github.com/user-attachments/assets/d5943eb5-ddc1-42c9-a584-fe1fe4d8323f)

**Comment by jpveooys** [comment]
Dupe of https://github.com/Royal-Navy/design-system/issues/3528? (If the warning is the reason it's not showing...)

**Comment by m7kvqbe1** [comment]
Closing as it's a dupe of https://github.com/Royal-Navy/design-system/issues/3528.
