### ISSUE TITLE
DataGrid: Manual sorting, how?

### ISSUE THREAD

**Issue by psyvision** [Royal-Navy/design-system#3970]
I'm upgrading from the old `@defencedigital/*` packages to the modern `@royalnavy` packages and we are wanting to migrate from a custom Table component to the design system one.  However, we do server side pagination and server side sorting and I can't get server side sorting to work with the DataGrid component.

When the following-ish code is used, on initial render items are outputted to  the console (due to the `debugAll`) however none of the subsequent console logs happen when toggling the column sort.

### Steps to reproduce

```typescript
  const columns = [...]
  const items = [...]

  return (<DataGrid
        debugAll
        columns={columns}
        data={items}
        enableSorting={true}
        manualSorting
        manualPagination={true}
        onColumnOrderChange={(x) => console.log(x)}
        onStateChange={(x) => { console.log(x) }}
        onPageChange={(x, y) => console.log(x, y)}
  />)
```

### Minimal reproduction

Unable to provide one at the moment (private internal repo).

**Comment by m7kvqbe1** [comment]
Unfortunately the the current implementation doesn't yet support manual / server side sorting.

The good news is it's a relatively quick and simple change to get it working so i've done it tonight: https://github.com/Royal-Navy/design-system/pull/3971.

**Comment by psyvision** [comment]
Thanks Tom, that's a wicked turnaround time!  I had started to hack a local version together yesterday but this looks to do the job nicely, I will grab that branch today and see if I can build a local copy to trial it.  Thanks again.

**Comment by m7kvqbe1** [comment]
No problem, my pleasure. This has been merged now and will ship as part of the the nightly build.

**Comment by psyvision** [comment]
Many thanks!
