### ISSUE TITLE
Icons affect button height

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#402]
When an icon is added to a Button the height of the icon can change the height of the button.

For a single button this may be ok, but when using multiple buttons or a button group the difference is obvious.

<img width="242" alt="Screenshot 2019-10-30 at 13 37 38" src="https://user-images.githubusercontent.com/48056118/67862763-a5bf2600-fb1a-11e9-951d-4dae0baece11.png">

**Comment by hxltrhuxze** [comment]
FWIW, we'll definitely need to make sure the buttons are all the same height, regardless of if they're standalone or now.
