### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#407]
**Is your feature request related to a problem? Please describe.**
We've got a need for new icons in a current project that aren't in the Material set.

**Describe the solution you'd like**
Creation of new icons which match look and feel of Standards icons. Specifically:
* Anchor. Similar to https://www.flaticon.com/free-icon/boat-anchor_66698#term=anchor&page=1&position=26
* Speedo set to full / high speed (I don't like the one in the Material library). Similar to https://www.flaticon.com/free-icon/speedometer_597334#term=speedometer&page=1&position=22
* Speedo set to medium / half speed (I don't like the one in the Material library). Similar to https://www.flaticon.com/free-icon/speedometer_597334#term=speedometer&page=1&position=22
* Barrels (x2). Similar to https://www.flaticon.com/free-icon/two-metallic-barrels_78441#term=barrels&page=1&position=16

There may be more icons. I will add to this list as the need arises.

**Describe alternatives you've considered**
Icons temporarily sourced from flaticon.com

**Comment by ghost** [comment]
This needs to be looked at in the next couple of weeks for the exemplar project.

**Comment by hxltrhuxze** [comment]
<img width="561" alt="Screenshot 2019-12-05 at 16 54 22" src="https://user-images.githubusercontent.com/48090803/70257864-11805880-1783-11ea-9e7a-cc5e4a1c1629.png">

New Standards section in the icon library. Contains:
- speed slow
- speed med
- speed fast
- barrels
- anchor
