### ISSUE TITLE
Add tree shaking (PurgeCSS) to the CSS Framework

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#428]
Currently, the CSS Framework compiles a large number of utility classes. These are great for quickly styling an application, however there will inevitably be a number of classes that don't get used. This leads to unnecessary bloat.

To solve this, we should implement PurgeCSS (or something similar) to remove unneeded styles from the compiled framework.

**Comment by m7kvqbe1** [comment]
Is this now a bit redundant now that we are utilising SASS modules?

**Comment by hxltrhuxze** [comment]
We'll still want it as it'll allow us to remove all the utility classes that aren't being used. As we generate every variation in class form, a large majority won't be used in any specific application.

**Comment by hxltrhuxze** [comment]
We'll still want it as it'll allow us to remove all the utility classes that aren't being used. As we generate every variation in class form, a large majority won't be used in any specific application.

**Comment by hxltrhuxze** [comment]
This feature is now nullified in its current form, due to the `v3` adoption of Styled Components
