### ISSUE TITLE
Where do I put the logout button in Masthead?

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#444]
Working on a project and need to be able to show the user logged in in the top right and then allows them to easily logout but the top right avatar only accepts a link to a page and navitems can only be shown below the masthead but logout would be the only option.

Can Avatar allow you to have a popover appear below it with options to put the logout button in?

**Comment by hxltrhuxze** [comment]
The Logout button should be sat within a sheet that appears on clicking the avatar. These links are optional so should be up to the implementer to decide which ones they need.

<img width="171" alt="Screenshot 2020-06-18 at 12 31 28" src="https://user-images.githubusercontent.com/48090803/85015291-a404aa00-b15f-11ea-92da-04019e3f9c3d.png">
