### ISSUE TITLE
Modal - Can display modal only once

### ISSUE THREAD

**Issue by jk68mnpo** [Royal-Navy/design-system#505]
**Description**
Can display modal only once (if isOpen=true on initialisation) and successfully close. After it is closed, I can no longer reopen it as expected.

**Example Code Snippet**

```javascript
const [modalOpen, setModalOpen] = useState(false)
 
 return (
  <Button onClick={(_ => setModalOpen(true)}>Click me</Button>
  <Modal
    title="Example"
    isOpen={modalOpen}
    onClose={_ => setModalOpen(false)}
  />
 )
 ```

**Comment by m7kvqbe1** [comment]
This is a known issue that needs resolving. The internal state in the modal needs removing and the show/hide behaviour should be delegated to the consumer.

A workaround for now is to use routes:

https://github.com/Royal-Navy/coffee/blob/a4234b192553bc12dbcc02496e093909bf4fa260/src/pages/Subscriptions/index.jsx#L57
