### ISSUE TITLE
Cannot paginate table data

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#511]
**Describe the bug**
If I feed the table component data via the data prop and then that data changes (context: I slice a collection for pagination).

A re-render of the component isn't triggered because of the local state within the table component useTableData hook.

**Expected behavior**
Component reacts to changing data via prop.

**Additional context**
My use case is wanting to paginate a collection of table data.

**Comment by thyhjwb6** [comment]
This has now been released.
