### ISSUE TITLE
DatePicker - Calendar appears behind modal component

### ISSUE THREAD

**Issue by jk68mnpo** [Royal-Navy/design-system#530]
**Describe the bug**
When using the datepicker input within a modal, the calendar appears behind the modal

**To Reproduce**
1. Create a modal with the datepicker input as part of the body
2. Click on the input

**Applied temporary fix**
- Increased z-index of `tether-element` 

**Environment:**
 - Ubuntu
 - Chrome(69.0.81) and Firefox (69.0.1)

**Comment by m7kvqbe1** [comment]
The tether-element z-index needs to be set higher only when the contained component wrapper (`FloatingBox`) is set to be visible. 

In addition, currently the invisible Tether component prevents you from clicking on things below it. Maybe we could display none the parent Tether component based on the child FloatingBox open/closed state?
