### ISSUE TITLE
Upgrade to Yarn v2

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#606]
We need to upgrade to Yarn v2 - this resolves some issues with deep package resolutions.

**Comment by m7kvqbe1** [comment]
https://next.yarnpkg.com/advanced/migration

**Comment by m7kvqbe1** [comment]
This isn't as simple as first though and will potentially have an impact on the way we manage the monorepo with Lerna.

**Comment by hxltrhuxze** [comment]
Closing until required.
