### ISSUE TITLE
Toast Component

### ISSUE THREAD

**Issue by jk68mnpo** [Royal-Navy/design-system#620]
## Description
It's a way to communicate events / information to a user.

## Component classification

Is this component an atom, molecule or organism?
- [ x ] Atom

## Details / user needs
- Displays a title, a message and a severity
- Dismissible by the end user
- Slides in from the side of the screen (preferably from bottom right)

## Questions

Outstanding questions for the Product Owner, Designers or Developers.

## Definition of done
- [x] The Sketch file is updated with the component
- [x] There are screenshots of all component variations in this ticket
- [x] All states are included if applicable (default, hover, active, focus)
- [x] A design documentation PR is linked from this ticket
- [x] All questions laid out in this ticket have been resolved 
- [x] A pull request for a component must contain a fully tested, documented and finished component in a state it can be shared with partner developers

**Comment by m7kvqbe1** [comment]
It is my understanding that mocks already exist for this component.
