### ISSUE TITLE
Review and improve the READMEs in individual packages

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#644]
The READMEs in the individual packages appear to need some attention.

They include outdated information or are lacking information.

These files are used by NPM and should be in a good state.

**Comment by thyhjwb6** [comment]
This issue has been broken down into multiple issues for each package:
https://github.com/Royal-Navy/standards-toolkit/issues/718
https://github.com/Royal-Navy/standards-toolkit/issues/719
https://github.com/Royal-Navy/standards-toolkit/issues/720
https://github.com/Royal-Navy/standards-toolkit/issues/721
https://github.com/Royal-Navy/standards-toolkit/issues/722
