### ISSUE TITLE
The method used to raise events on components is inconsistent

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#645]
An example of this can be seen in `NumberInput`:

```
  onChange: (event: any) => void
```

A preferred approach might be:

```
  onChange: (event: React.ChangeEvent<{}>, value: number) => void
```

It is recommended that all components are audited to ensure a consistent approach. This will be a breaking change and needs to wait for `v3`.

**Comment by jpveooys** [comment]
There are also a few examples of using this style in the code base:

```
onFocus: React.FocusEventHandler<HTMLInputElement>
```
