### ISSUE TITLE
Tidy labels in GitHub

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#649]
We have a lot of redundant and confused labels within this repository. Let's tidy this up.

**Comment by m7kvqbe1** [comment]
Maybe put them all in a spreadsheet and we can review from there.

**Comment by elglup** [comment]
Existing GitHub labels reviewed and new GitHub labelling scheme agreed.  New labels now applied to the standard toolkit repo and old labels removed.
