### ISSUE TITLE
Issue with icon-library build exports

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#723]
There appears to be an issue with the icon library generated exports - the 2.2.1 build appears as such be broken.

Looks like this might be some kind of knock on effect from a dependency upgrade?

Note the warning at the bottom of this screenshot:

<img width="1482" alt="Screenshot 2020-03-12 at 14 04 40" src="https://user-images.githubusercontent.com/48086589/76529662-7cb88580-646a-11ea-94a2-98379666936c.png">

**Comment by thyhjwb6** [comment]
Closing this issue as it is done.
