### ISSUE TITLE
Remove generate-exports.sh from icon-library

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#744]
As part of #723 `rm src/icons/index.tsx` was added to remove the file which was causing issues. With the recent upgrade of `svgr`, it is now attempting to output `index.ts`. If we can use this file rather than our own custom `generate-exports.sh` it would be better as it is now confusing how this works.

**Comment by m7kvqbe1** [comment]
I've looked into this and I can't seem to get past the race condition issue with the @svgr/cli tool.

I've raised an issue here (https://github.com/gregberge/svgr/issues/433) and provided them with a repro branch in this repo.
