### ISSUE TITLE
Bad english in docs-site Alpha banner

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#775]
<img width="489" alt="Screenshot 2020-03-25 at 20 42 31" src="https://user-images.githubusercontent.com/48086589/77583557-31c25780-6ed9-11ea-843a-6942a7af9bdb.png">

>...will help us to improve it

**Comment by el7h1rw2** [comment]
After much deliberation, we, the undersigned, elected to withdraw the aforementioned issue.
