### ISSUE TITLE
Create & define repo security policy (public facing)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#799]

**Comment by elglup** [comment]
As per GitHub best practice we should define security policy for the standards toolkit repo.
Aim:
To provide instructions for responsibly reporting security vulnerabilities in the project.

Acceptance criteria:

Create a security.md file which includes -
- [x] disclosure policy
- [x] security update policy
- [x] any security related configuration
- [x] known security gaps & future enhancements
