### ISSUE TITLE
(Spike) Smoke testing NPM package

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#816]
This is to prove the concept of using a private NPM repo and using NPM command line to publish. This is not to set it up as a Circle job.

Acceptance criteria:
- [x] Publish package to private repo (Verdaccio)
- [x] Consume to an extent that we know there is an issue

**Comment by elglup** [comment]
Agreed we will create a part II Spike to cover extended requirements for smoke testing

**Comment by elglup** [comment]
https://docs.google.com/document/d/1VrRt0aZKwYSbeOa5b2SzOXb3A3V1Vz09J_t_IMVm69M/edit
