### ISSUE TITLE
Add to test coverage across components

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#848]
Fill in the gaps:

![Screenshot 2020-04-15 at 07 17 02](https://user-images.githubusercontent.com/56078793/79449270-d3b9f900-7fda-11ea-9cd0-b78fb7255125.png)

**Acceptance criteria**
- [ ] Dropdown
- [ ] Pagination
- [ ] PhaseBanner
- [ ] Select
- [ ] Switch

**Comment by thyhjwb6** [comment]
This is covered by smaller tickets for each component.
