### ISSUE TITLE
"Do I need a consultation" document

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#911]
This document forms part of the Contribution Guidelines (#910), aimed at helping DS users consume and contribute to the Royal Navy Design System. The Design System team offers consultations for internal application users so they can get support and feedback from the DS team.

This document outlines what a consultation is and how it can benefit the requesting application team. It also contains links to other documents (including "How to extend the Design System") if the application team decides against requesting a consultation.

## Work items
- [ ] "Do I need a consultation" document

**Comment by el7h1rw2** [comment]
This work has been completed via a different route.
