### ISSUE TITLE
"DST Consultation agenda template" Document

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#913]
This document provides an outline agenda for the Design System team consultations. It should help the requesting application teams highlight the areas they would like to focus on for their consultation.

## Work items
- [ ] "DST Consultation agenda template" Document

**Comment by mahi-love** [comment]
U right the use us like nothing happens to us and  after that not replying even Emails they neeed to pay back our time pr mint and give us complete right as they do ... any time u finesse through u under buss

**Comment by seb655** [comment]
Hi, my name is Sébastien Côté my from hits Canada Québec And my number
ticket is MRP-545-76536 and Ami ID= ami-DC1F74bO12b1506F7 too Github im
reçeive full PDF is FORM too one account at my adress gmail is amount
attribuate at my name? Thanks

**Comment by seb655** [comment]
Hi, My name is Sébastien Côté my from hits Canada Québec And i have full
informations github too Mahilove and Ami ID=ami-Dc1F74bo12b1506f7 and my
number ticket is MRP-545-76536

**Comment by el7h1rw2** [comment]
This work has been completed via a different route.
