### ISSUE TITLE
Implement new experimental Sidebar

### ISSUE THREAD

**Issue by hxltrhuxze** [Royal-Navy/design-system#965]
In its current form, the sidebar is lacking in functionality and overall usefulness. This iteration aims to provide DS users with a modular and adaptable sidebar.

<img width="1192" alt="Screenshot 2020-05-15 at 12 24 57" src="https://user-images.githubusercontent.com/48090803/82045504-1ab51000-96a7-11ea-8e95-ea67bcb2a749.png">

### Why v3?
In order for the new sidebar capabilities to work, we have to break a few prop APIs and layouts. This will require effort for the DS user to implement, so this improvement is scheduled for the next breaking release (`v3`). The main breaking changes that are needed are:

- A wrapper to surround the main application, allowing the main app content to resize when the sidebar is expanded and contracted
- More useful props (e.g. `user` to apply the full name of the user to the sidebar, instead of just initials)
- Revamped Sidebar nav items, allowing for contextual menus

**Comment by hxltrhuxze** [comment]
On hold until we approach v3.

**Comment by jk68mnpo** [comment]
RSTA would like to increase the priority of this if possible? The appearance of the menu when clicking/hovering on the user icon would be particularly useful for what we would like to achieve.

Is it possible to have onClick functionality rather than only providing links for that menu also?

**Comment by el7h1rw2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 48 Goals](https://trello.com/c/N1MYhhs0/43-sprint-48-goals)
