### ISSUE TITLE
Dismissible Banner

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#975]
### Description
For one of our exemplar projects (and a number of others) we have identified the need for a tile that can be hidden by users after they have read the content.

This would take the form of a checkbox with label reading "Don't show the message again". The message should then be hidden for a set amount of time:

- indefinitely
- until the content of the tile is changed
- for a set amount of time e.g. one year

I imagine this would be set by placing a cookie on the user's machine.

We may also want to tie the display of the tile to other types of scenario, for example the user's account or Application settings.
![dismiss-able](https://user-images.githubusercontent.com/52033457/82316445-b656c100-99c4-11ea-81d2-2c7575e11d6e.png)

**Comment by hxltrhuxze** [comment]
## Dismissible Banner

The **Dismissible Banner** sits at the top of a page. It provides context, particularly for users who haven't used a particular app/feature yet. It has the ability to dismiss, and includes the ability for the app to remember if the user has dismissed this (semi-) permanently. 

<img width="590" alt="Screenshot 2020-06-15 at 16 14 58" src="https://user-images.githubusercontent.com/48090803/84674898-73383100-af23-11ea-8c24-c8c25406d879.png">

We should also provide a banner frame without content:
<img width="580" alt="Screenshot 2020-06-15 at 16 15 07" src="https://user-images.githubusercontent.com/48090803/84674908-759a8b00-af23-11ea-80a1-3ed5fde89981.png">

And without the checkbox:
<img width="583" alt="Screenshot 2020-06-15 at 16 15 12" src="https://user-images.githubusercontent.com/48090803/84674909-759a8b00-af23-11ea-9742-e42a94f444b6.png">

**Comment by thyhjwb6** [comment]
Documentation will be picked up in a separate ticket.
