### ISSUE TITLE
Quick-access tiles (list variation)

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#976]
### Description
For an exemplar project, we need a new variation of a list component.

In this particular scenario the list is used to link to items (think recenty-opened-files).

This component has a heading, description and button. The entire list item should be clickable.

Please ensure the colour contrast matches accessibility guidelines - the example below has not been checked.

![quick-access-tiles](https://user-images.githubusercontent.com/52033457/82316633-02a20100-99c5-11ea-9073-24861a9123f5.png)

**Comment by hxltrhuxze** [comment]
List container with links.

**Comment by hxltrhuxze** [comment]
This list component provides a clickable list of items.


<img width="1115" alt="Screenshot 2020-06-29 at 16 31 32" src="https://user-images.githubusercontent.com/48090803/86025377-02663e00-ba26-11ea-8a0f-3b8eff889a3d.png">

#### Notes
- Removed the "Action" button from each row as this should be reserved for a singular, more important action.
- Colours now pass `a11y` checks
- When hovering on a list item, every item _except_ the active item changes its background to `neutral, 000`
