### ISSUE TITLE
Extend <select> functionality

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#977]
### Description
For an exemplar project, we have identified the need for a select / drop-down that functions as follows:

- A 'classic' selection box
- As a type-to-search box, with search suggestions appearing below the text
- An 'add to list' function. If the typed search function does not result in a selection, the typed entry becomes a new item

Example context - select a ship:

- Pick an existing ship from a list
- Type to search for an existing ship in the list
- If ship is not on the list, add new ship to list

![select](https://user-images.githubusercontent.com/52033457/82319907-49462a00-99ca-11ea-8ba1-26eddae8faa9.png)

**Comment by antictor** [comment]
The project also needs the ability to add an icon/avatar to the right side

**Comment by k9dh3zij** [comment]
I've added this as an enhancement for v3 - which comes under this epic #1493

**Comment by k9dh3zij** [comment]
This has been designed in the spec, but will not be part of the initial release of v3
