### ISSUE TITLE
RangeSlider with user defined thresholds

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#979]
### Description
An exemplar project has identified the need for coloured range selector.

To be clear, the need isn't to have the colour change depending on the value of the slider, it's just to change the colour of the whole range selector.

It was suggested that red, amber and green might be suitable colours, but I would suggest allowing the range slider to adopt any colour from the Design System colour palette would be best.

![range-selectors](https://user-images.githubusercontent.com/52033457/82321210-65e36180-99cc-11ea-920e-267b6025d1cf.png)

**Comment by hxltrhuxze** [comment]
We're implementing a "threshold" version of this component.

The devs will be able to supply thresholds for the range selector, changing the colour appropriately. When the user then moves the range slider handle, the range slider will change colour based on its position of the handle. The range slider can have up to three colours - `action`, `warning`, and `danger`. 

The order of the colours are `danger`, then `warning`, and then the default `action`. `danger` and `warning` are both optional, and their limits are custom set via prop values.

**Comment by m7kvqbe1** [comment]
Single threshold:
```
[---Colour Danger---|---Colour Action**HANDLE**|--- Non-coloured---]
```

Double threshold:
```
[---Colour Danger---|---Colour Warning---|---Colour Action**HANDLE**|--- Non-coloured---]
```

**Comment by m7kvqbe1** [comment]
Value of each threshold is optional, user defined and arbitrary.
