### ISSUE TITLE
Popover with close button

### ISSUE THREAD

**Issue by ghost** [Royal-Navy/design-system#980]
### Description
The default behaviour for closing popovers is for the user to click or tap anywhere outside the popover, however in some cases (in an exemplar project) it is preferable for there to also be a visible 'X' button to close, located in the top-right corner of the popover.

![popovers](https://user-images.githubusercontent.com/52033457/82322575-a47a1b80-99ce-11ea-9e2e-50d3c8215e80.png)

**Comment by thyhjwb6** [comment]
The `Popover` component will not be changed as it closes `onMouseLeave`.
