### ISSUE TITLE
DatePicker doesn't work with Formik

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#984]
The DateRange component examples all seem to work as a regular form component but if the form is a Formik based form the component doesn't work.

When a DatePicker is included in the formik form the following warning is reported:

`Warning: Failed prop type: You provided a `value` prop to a form field without an 'onChange' handler. This will render a read-only field. If the field should be mutable use 'defaultValue'. Otherwise, set either 'onChange' or 'readOnly'.`

If the user changes a value the page crashes:

`Formik.tsx:617 Uncaught TypeError: Cannot read property 'type' of undefined`

---------

Some of the issues may be caused by Fromik expecting the value to be put in the form using the value property and the onChange type to match.

Would it be possible to set the initial value using an object and have the same data type used for onChange? Maybe set the name property to be fieldname.startDate and same for endDate

An example can be found here: https://github.com/antictor/daterange/blob/master/src/App.tsx

**Comment by antictor** [comment]
<img width="1392" alt="Screenshot 2020-05-19 at 14 29 22" src="https://user-images.githubusercontent.com/48056118/82332354-31c46c80-99dd-11ea-9a9e-d803676e9c2e.png">
<img width="1392" alt="Screenshot 2020-05-19 at 14 29 13" src="https://user-images.githubusercontent.com/48056118/82332362-35f08a00-99dd-11ea-909f-354fb7ad1be8.png">

**Comment by antictor** [comment]
To add to comments, fields generally raise a synthetic event for onChange but this field just send back data. It should act like a regular field.

Getting the same onChange error on regular forms that don't use Formik

**Comment by m7kvqbe1** [comment]
The console warning comes from some DatePicker implementation detail - the input element used to display the currently selected date(s) was missing a `readOnly` attribute (https://github.com/Royal-Navy/design-system/pull/1072).

In regards to DatePicker Formik usage i've just pushed an example story you can see here:

https://github.com/Royal-Navy/design-system/blob/1bb792db69273a6496a659f3e721ff48e276182d/packages/react-component-library/src/components/DatePicker/DatePicker.stories.tsx#L84

Being a non standard form component the DatePicker should be supplied a custom `onChange` handler from within which you invoke the Formik `setFieldValue` method.

There is a bit more chat about using custom form fields with Formik here:

https://stackoverflow.com/questions/52271766/how-to-use-custom-input-with-formik-in-react

We plan to conduct a review across the board of all the 'form' components to make usage with third party libraries like Formik as elegant and consistent as possible.

I've added a note for us to look at changing the signature of the `onChange` event parameter to the following:

```js
const e = {
  target: {
    name,
    value
  }
}
```

This is a breaking change and will be included in our next major release.
