### ISSUE TITLE
Select component z-index thing

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#986]
Create a page with a Select component
Give it some options
Put some layout below it.

When you open the select it drops down but content underneath is still visible and can be interacted with.

![May-19-2020 21-10-44](https://user-images.githubusercontent.com/48056118/82373252-3ad13000-9a15-11ea-95f0-4c7e80fa20c1.gif)

**Comment by thyhjwb6** [comment]
Attempted to reproduce this one a few times with no success.

**Comment by antictor** [comment]
I'll create a standalone app by Monday that demonstrates this

**Comment by thyhjwb6** [comment]
By rolling back `_btn.scss` to `b0454490e494f4fa3e8d8c3ea985991b636f2994` I can reproduce the issue but using the current version the issue is fixed.
