### ISSUE TITLE
Arbitrary props need to be drilled in Select component

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#989]
>how can i get hold of the select component and fire change event?
>
>the data-testid i am giving to select component is getting ignored..
>
>screen.getByTestId is not working
>
>but if i do screen.getByLabelText I am getting input html component. But when I fire change event doesnt get to my change handler...

**Comment by jk68mnpo** [comment]
This is still a problem for me in the 2.9.0 release, it looks like it was merged into the master branch before that release was shipped.

Example Code Snippet
`<Select data-testid="app-select-input"/>`

Cannot see data-testid in the dom
